<?php



$dictionary['fte_UsageTracking'] = array(
    'table' => 'fte_usagetracking',
    'audited' => true,
    'activity_enabled' => false,
    'acls' => [
        "DotbACLUsageTracking" => true
    ],
    'duplicate_merge' => true,
    'fields' => array(
        'name' =>
            array(
                'name' => 'name',
                'vname' => 'LBL_NAME',
                'type' => 'name',
                'dbType' => 'varchar',
                'len' => 255,
                'unified_search' => true,
                'full_text_search' =>
                    array(
                        'enabled' => true,
                        'searchable' => true,
                        'boost' => 1.55,
                    ),
                'required' => true,
                'importable' => 'required',
                'readonly' => true,
                'duplicate_merge' => 'enabled',
                'merge_filter' => 'selected',
                'duplicate_on_record_copy' => 'always',
            ),
        'action' =>
            array(
                'required' => false,
                'name' => 'action',
                'vname' => 'LBL_FTE_UT_ACTION',
                'type' => 'enum',
                'massupdate' => true,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'enabled',
                'duplicate_merge_dom_value' => '1',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'default' => '',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'options' => 'fte_ut_action_list',
                'dependency' => false,
            ),
        'parent_name' =>
            array(
                'required' => false,
                'source' => 'non-db',
                'name' => 'parent_name',
                'vname' => 'LBL_RELATED_TO',
                'type' => 'parent',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'enabled',
                'duplicate_merge_dom_value' => '1',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'calculated' => false,
                'len' => 36,
                'size' => '20',
                'options' => 'parent_type_display',
                'default' => '',
                'type_name' => 'parent_type',
                'id_name' => 'parent_id',
                'parent_type' => 'record_type_display',
                'studio' => 'visible',
            ),
        'parent_type' =>
            array(
                'required' => false,
                'name' => 'parent_type',
                'vname' => 'LBL_PARENT_TYPE',
                'type' => 'parent_type',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'enabled',
                'duplicate_merge_dom_value' => 1,
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'calculated' => false,
                'len' => 255,
                'size' => '20',
                'dbType' => 'varchar',
                'studio' => 'hidden',
                'group' => 'parent_name',
            ),
        'parent_id' =>
            array(
                'required' => false,
                'name' => 'parent_id',
                'vname' => 'LBL_PARENT_ID',
                'type' => 'id',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'enabled',
                'duplicate_merge_dom_value' => 1,
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'calculated' => false,
                'len' => 36,
                'size' => '20',
            ),
        'action_identifier' =>
            array(
                'required' => false,
                'name' => 'action_identifier',
                'vname' => 'LBL_ACTION_IDENTIFIER',
                'type' => 'varchar',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'enabled',
                'duplicate_merge_dom_value' => '1',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'default' => '',
                'full_text_search' =>
                    array(
                        'enabled' => '0',
                        'boost' => '1',
                        'searchable' => false,
                    ),
                'calculated' => false,
                'len' => '255',
                'size' => '20',
            ),
        'related_module_name' =>
            array(
                'required' => true,
                'name' => 'related_module_name',
                'vname' => 'LBL_RELATED_MODULE',
                'type' => 'varchar',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'enabled',
                'duplicate_merge_dom_value' => '1',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'default' => "",
                'full_text_search' =>
                    array(
                        'enabled' => '0',
                        'boost' => '1',
                        'searchable' => false,
                    ),
                'calculated' => false,
                'len' => '255',
                'size' => '20',
                'group' => 'parent_name',
            ),
        'platform' =>
            array(
                'required' => false,
                'name' => 'platform',
                'vname' => 'LBL_FTE_UT_PLATFORM',
                'type' => 'varchar',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'enabled',
                'duplicate_merge_dom_value' => '1',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'default' => "Desktop",
                'full_text_search' =>
                    array(
                        'enabled' => '0',
                        'boost' => '1',
                        'searchable' => false,
                    ),
                'calculated' => false,
                'len' => '255',
                'size' => '20',
            ),
    ),
    'relationships' => array(),
    'optimistic_locking' => true,
    'unified_search' => true,
    'full_text_search' => true,
);

if (!class_exists('VardefManager')) {
}
VardefManager::createVardef('fte_UsageTracking', 'fte_UsageTracking', array('basic', 'assignable', 'taggable'));