<?php
$dictionary['J_PaymentDetail']['fields']['e_invoice_token'] =array(
    'name' => 'e_invoice_token',
    'type' => 'varchar',
    'label' => 'LBL_E_INVOICE_TOKEN',
    'len' => '100',
);
$dictionary['J_PaymentDetail']['fields']['transaction_id'] =array(
    'name' => 'transaction_id',
    'type' => 'varchar',
    'label' => 'LBL_TRANSACTION_ID',
    'len' => '100',
);
$dictionary['J_PaymentDetail']['fields']['text_currency'] =array(
    'name' => 'text_currency',
    'type' => 'varchar',
    'label' => 'LBL_TEXT_CURRENCY',
    'len' => '100',
    'source' => 'non-db',
);

$dictionary['J_PaymentDetail']['fields']['quote_id'] =array(
    'name' => 'quote_id',
    'vname' => 'LBL_QUOTE_ID',
    'type' => 'id',
    'required'=>true,
    'reportable'=>false,
    'comment' => '',
    'default'=> ''
);

$dictionary['J_PaymentDetail']['fields']['quote_name'] =array(
    'name' => 'quote_name',
    'rname' => 'name',
    'id_name' => 'quote_id',
    'vname' => 'LBL_QUOTE_NAME',
    'type' => 'relate',
    'link' => 'quote_link',
    'table' => 'quotes',
    'isnull' => 'true',
    'module' => 'Quotes',
    'dbType' => 'varchar',
    'len' => 'id',
    'reportable'=>true,
    'source' => 'non-db',
    'auto_populate' => true,
    'populate_list' =>
        array (
            'unpaid_amount' => 'payment_amount',
            'parent_type' => 'parent_type',
            'parent_id'=> 'parent_id',
            'parent_name'=> 'parent_name',
        ),
    'dependency' => 'equal($payment_type, "Normal")',
);

$dictionary['J_PaymentDetail']['fields']['quote_link'] =array(
    'name' => 'quote_link',
    'type' => 'link',
    'relationship' => 'quote_paymentdetails',
    'link_type' => 'one',
    'side' => 'right',
    'source' => 'non-db',
    'vname' => 'LBL_QUOTE_NAME',
    'id_name' => 'quote_id',
);

$dictionary['J_PaymentDetail']['fields']['status'] =array (
    'required' => false,
    'name' => 'status',
    'vname' => 'LBL_STATUS',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'default' => 'Paid',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => 10,
    'size' => '20',
    'options' => 'status_paymentdetail_list',
    'studio' => 'visible',
    'dependency' => false,
);

$dictionary['J_PaymentDetail']['fields']['card_type'] = array (
    'required' => false,
    'name' => 'card_type',
    'vname' => 'LBL_CARD_TYPE',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => '',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'card_type_payments_list',
    'studio' => 'visible',
    'dependency' => 'equal($payment_method, "Card")',
);

$dictionary['J_PaymentDetail']['fields']['pos_code'] = array (
    'required' => false,
    'name' => 'pos_code',
    'vname' => 'LBL_POS_CODE',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => 'Method Note',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => '100',
    'size' => '20',
    'dependency' => 'equal($payment_method, "Card")',
);
$dictionary['J_PaymentDetail']['fields']['bank_account'] = array (
    'required' => false,
    'name' => 'bank_account',
    'vname' => 'LBL_BANK_ACCOUNT',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => '',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'bank_name_list',
    'studio' => 'visible',
    'dependency' => 'equal($payment_method, "Bank Transfer")',
);

$dictionary['J_PaymentDetail']['fields']['bank_account'] = array (
    'required' => false,
    'name' => 'bank_account',
    'vname' => 'LBL_BANK_ACCOUNT',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => '',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'bank_name_list',
    'studio' => 'visible',
    'dependency' => 'equal($payment_method, "Bank Transfer")',
);

$dictionary['J_PaymentDetail']['fields']['payment_type'] =array(
    'required' => false,
    'name' => 'payment_type',
    'vname' => 'LBL_PAYMENT_TYPE',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => 'Deposit',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => 20,
    'size' => '20',
    'options' => 'payment_type_list_dom',
    'studio' => 'visible',
);
//
$dictionary['J_PaymentDetail']['fields']['parent_type'] =array(
    'name' => 'parent_type',
    'vname' => 'LBL_PARENT_TYPE',
    'type' => 'parent_type',
    'dbType' => 'varchar',
    'required' => false,
    'group' => 'parent_name',
    'options' => 'parent_type_display_custom',
    'len' => 255,
    'studio' => array('wirelesslistview' => false),
    'comment' => 'The Dotb object to which the call is related',
    'default' => 'Accounts'
);
$dictionary['J_PaymentDetail']['fields']['parent_id'] =array(
    'name' => 'parent_id',
    'vname' => 'LBL_LIST_RELATED_TO_ID',
    'type' => 'id',
    'group' => 'parent_name',
    'reportable' => false,
    'comment' => 'The ID of the parent Dotb object identified by parent_type',
    'required' => true
);

$dictionary['J_PaymentDetail']['fields']['parent_name'] =array(
    'name' => 'parent_name',
    'parent_type' => 'record_type_display',
    'type_name' => 'parent_type',
    'id_name' => 'parent_id',
    'vname' => 'LBL_LIST_RELATED_TO',
    'type' => 'parent',
    'group' => 'parent_name',
    'source' => 'non-db',
    'options' => 'parent_type_display_custom',
    'studio' => true,
    'required' => true,
//    'dependency' => 'equal($payment_type, "Deposit")',
);

$dictionary['J_PaymentDetail']['fields']['currency_id'] =array(
    'required' => false,
    'name' => 'currency_id',
    'vname' => 'LBL_CURRENCY_ID',
    'type' => 'currency_id',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => 1,
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'calculated' => false,
    'len' => 36,
    'size' => '20',
    'dbType' => 'id',
    'studio' => false,
    'function' => 'getCurrencies',
    'function_bean' => 'Currencies',
);

$dictionary['J_PaymentDetail']['fields']['base_rate'] =array(
    'required' => false,
    'name' => 'base_rate',
    'vname' => 'LBL_CURRENCY_RATE',
    'type' => 'decimal',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => 1,
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'calculated' => false,
    'len' => 26,
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 2,
    'label' => 'LBL_CURRENCY_RATE',
    'studio' => false,
);

