<?php

$viewdefs['base']['view']['dri-workflow'] = array (
    'activityButtons' => array (
        array(
            'type' => 'actiondropdown',
            'name' => 'main_dropdown',
            'notCustomButton' => true,
            'buttons' => array(
                array(
                    'type' => 'rowaction',
                    'icon' => 'fa-check icon-check',
                    'name' => 'activity_complete_button',
                    'event' => 'activity:complete_button:click',
                    'tooltip' => 'LBL_COMPLETE_BUTTON_TITLE',
                    'acl_action' => 'edit',
                    'label' => ' ',
                ),
                array(
                    'type' => 'rowaction',
                    'icon' => 'fa-play icon-play',
                    'name' => 'activity_start_button',
                    'event' => 'activity:start_button:click',
                    'acl_action' => 'edit',
                    'label' => 'LBL_START_BUTTON_TITLE',
                ),
                array(
                    'type' => 'rowaction',
                    'icon' => 'fa-eye icon-eye-open',
                    'name' => 'activity_preview_button',
                    'event' => 'activity:preview_button:click',
                    'label' => 'LBL_PREVIEW',
                    'acl_action' => 'view',
                ),
                array(
                    'type' => 'rowaction',
                    'icon' => 'fa-pencil icon-pencil',
                    'name' => 'activity_edit_button',
                    'event' => 'activity:edit_button:click',
                    'acl_action' => 'edit',
                    'label' => 'LBL_EDIT_BUTTON_TITLE',
                ),
                array(
                    'type' => 'rowaction',
                    'icon' => 'fa-user icon-user',
                    'name' => 'activity_add_sub_task_button',
                    'event' => 'stage:add_sub_task_button:click',
                    'acl_action' => 'edit',
                    'acl_module' => 'Tasks',
                    'label' => 'LBL_ADD_CJ_SUB_TASK_BUTTON_TITLE',
                ),
                array(
                    'type' => 'rowaction',
                    'icon' => 'fa-calendar icon-calendar',
                    'name' => 'activity_add_sub_meeting_button',
                    'event' => 'stage:add_sub_meeting_button:click',
                    'acl_action' => 'edit',
                    'acl_module' => 'Meetings',
                    'label' => 'LBL_ADD_CJ_SUB_MEETING_BUTTON_TITLE',
                ),
                array(
                    'type' => 'rowaction',
                    'icon' => 'fa-phone icon-phone',
                    'name' => 'activity_add_sub_call_button',
                    'event' => 'stage:add_sub_call_button:click',
                    'acl_action' => 'edit',
                    'acl_module' => 'Calls',
                    'label' => 'LBL_ADD_CJ_SUB_CALL_BUTTON_TITLE',
                ),
                array(
                    'type' => 'rowaction',
                    'icon' => 'fa-user icon-user',
                    'name' => 'activity_assign_me_button',
                    'event' => 'activity:assign_me_button:click',
                    'acl_action' => 'edit',
                    'label' => 'LBL_ASSIGN_ME_BUTTON_TITLE',
                ),
                array(
                    'type' => 'rowaction',
                    'icon' => 'fa-times icon-remove',
                    'name' => 'activity_not_applicable_button',
                    'event' => 'activity:not_applicable_button:click',
                    'acl_action' => 'edit',
                    'label' => 'LBL_NOT_APPLICABLE_BUTTON_TITLE',
                ),
            ),
        ),
    ),
    'activityChildButtons' => array (
        array(
            'type' => 'actiondropdown',
            'notCustomButton' => true,
            'name' => 'main_dropdown',
            'buttons' => array(
                array(
                    'type' => 'rowaction',
                    'icon' => 'fa-check icon-check',
                    'name' => 'activity_complete_button',
                    'event' => 'activity:complete_button:click',
                    'tooltip' => 'LBL_COMPLETE_BUTTON_TITLE',
                    'acl_action' => 'edit',
                    'label' => ' ',
                ),
                array(
                    'type' => 'rowaction',
                    'icon' => 'fa-play icon-play',
                    'name' => 'activity_start_button',
                    'event' => 'activity:start_button:click',
                    'acl_action' => 'edit',
                    'label' => 'LBL_START_BUTTON_TITLE',
                ),
                array(
                    'type' => 'rowaction',
                    'icon' => 'fa-eye icon-eye-open',
                    'name' => 'activity_preview_button',
                    'event' => 'activity:preview_button:click',
                    'label' => 'LBL_PREVIEW',
                    'acl_action' => 'view',
                ),
                array(
                    'type' => 'rowaction',
                    'icon' => 'fa-pencil icon-pencil',
                    'name' => 'activity_edit_button',
                    'event' => 'activity:edit_button:click',
                    'acl_action' => 'edit',
                    'label' => 'LBL_EDIT_BUTTON_TITLE',
                ),
                array(
                    'type' => 'rowaction',
                    'icon' => 'fa-user icon-user',
                    'name' => 'activity_assign_me_button',
                    'event' => 'activity:assign_me_button:click',
                    'acl_action' => 'edit',
                    'label' => 'LBL_ASSIGN_ME_BUTTON_TITLE',
                ),
                array(
                    'type' => 'rowaction',
                    'icon' => 'fa-times icon-remove',
                    'name' => 'activity_not_applicable_button',
                    'event' => 'activity:not_applicable_button:click',
                    'acl_action' => 'edit',
                    'label' => 'LBL_NOT_APPLICABLE_BUTTON_TITLE',
                ),
            ),
        ),
    ),
    'stageButtons' => array (
        array(
            'type' => 'actiondropdown',
            'name' => 'main_dropdown',
            'notCustomButton' => true,
            'buttons' => array(
                array(
                    'type' => 'rowaction',
                    'icon' => 'fa-pencil icon-pencil',
                    'name' => 'stage_edit_button',
                    'event' => 'stage:edit_button:click',
                    'tooltip' => 'LBL_EDIT_BUTTON_TITLE',
                    'acl_action' => 'edit',
                    'label' => ' ',
                ),
                array(
                    'type' => 'rowaction',
                    'icon' => 'fa-user icon-user',
                    'name' => 'stage_add_task_button',
                    'event' => 'stage:add_task_button:click',
                    'acl_action' => 'edit',
                    'acl_module' => 'Tasks',
                    'label' => 'LBL_ADD_TASK_BUTTON_TITLE',
                ),
                array(
                    'type' => 'rowaction',
                    'icon' => 'fa-calendar icon-calendar',
                    'name' => 'stage_add_meeting_button',
                    'event' => 'stage:add_meeting_button:click',
                    'acl_action' => 'edit',
                    'acl_module' => 'Meetings',
                    'label' => 'LBL_ADD_MEETING_BUTTON_TITLE',
                ),
                array(
                    'type' => 'rowaction',
                    'icon' => 'fa-phone icon-phone',
                    'name' => 'stage_add_call_button',
                    'event' => 'stage:add_call_button:click',
                    'acl_action' => 'edit',
                    'acl_module' => 'Calls',
                    'label' => 'LBL_ADD_CALL_BUTTON_TITLE',
                ),
                array(
                    'type' => 'rowaction',
                    'icon' => 'fa-times icon-remove',
                    'name' => 'stage_delete_button',
                    'event' => 'stage:delete_button:click',
                    'acl_action' => 'delete',
                    'label' => 'LBL_DELETE_STAGE_BUTTON_TITLE',
                ),
            ),
        ),
    ),
    'topButtons' => array (
        array(
            'type' => 'actiondropdown',
            'name' => 'main_dropdown',
            'notCustomButton' => true,
            'buttons' => array(
                array(
                    'type' => 'rowaction',
                    'name' => 'journey_add_stage_button',
                    'event' => 'journey:add_stage_button:click',
                    'acl_action' => 'edit',
                    'acl_module' => 'DRI_SubWorkflows',
                    'label' => 'LBL_ADD_STAGE_BUTTON_TITLE',
                ),
                array(
                    'type' => 'rowaction',
                    'icon' => 'fa-reorder icon-reorder',
                    'name' => 'journey_view_button',
                    'event' => 'journey:view_button:click',
                    'acl_action' => 'view',
                    'acl_module' => 'DRI_Workflows',
                    'label' => 'LBL_VIEW_JOURNEY_BUTTON_TITLE',
                ),
                array(
                    'type' => 'rowaction',
                    'icon' => 'fa-cog icon-cog',
                    'name' => 'journey_configure_template_button',
                    'event' => 'journey:configure_template_button:click',
                    'acl_action' => 'view',
                    'acl_module' => 'DRI_Workflow_Templates',
                    'label' => 'LBL_CONFIGURE_TEMPLATE_BUTTON_TITLE',
                ),
                array(
                    'type' => 'rowaction',
                    'icon' => 'fa-ban icon-ban',
                    'name' => 'journey_cancel_button',
                    'event' => 'journey:cancel_button:click',
                    'acl_action' => 'edit',
                    'acl_module' => 'DRI_Workflows',
                    'label' => 'LBL_CANCEL_JOURNEY_BUTTON_TITLE',
                ),
                array(
                    'type' => 'rowaction',
                    'icon' => 'fa-archive icon-archive',
                    'name' => 'journey_archive_button',
                    'event' => 'journey:archive_button:click',
                    'acl_action' => 'edit',
                    'acl_module' => 'DRI_Workflows',
                    'label' => 'LBL_ARCHIVE_JOURNEY_BUTTON_TITLE',
                ),
                array(
                    'type' => 'rowaction',
                    'icon' => 'fa-archive icon-archive',
                    'name' => 'journey_unarchive_button',
                    'event' => 'journey:unarchive_button:click',
                    'acl_action' => 'edit',
                    'acl_module' => 'DRI_Workflows',
                    'label' => 'LBL_UNARCHIVE_JOURNEY_BUTTON_TITLE',
                ),
                array(
                    'type' => 'rowaction',
                    'icon' => 'fa-times icon-remove',
                    'name' => 'journey_delete_button',
                    'event' => 'journey:delete_button:click',
                    'acl_action' => 'delete',
                    'acl_module' => 'DRI_Workflows',
                    'label' => 'LBL_DELETE_BUTTON_TITLE',
                ),
            ),
        ),
    ),
    'last_state' => array (
        'id' => 'dri-workflow',
        'defaults' => array (
            'show_more' => 'less',
        ),
    ),
);
