<?php
$viewdefs['Calls'] = array(
    'base' => array(
        'view' => array(
            'list' => array(
                'panels' => array(
                    array(
                        'name' => 'panel_header',
                        'label' => 'LBL_PANEL_1',
                        'fields' => array(
                            array(
                                'label' => 'LBL_LIST_SUBJECT',
                                'enabled' => true,
                                'default' => true,
                                'link' => true,
                                'name' => 'name',
                                'related_fields' => array(
                                    0 => 'repeat_type',
                                ),
                                'width' => 'small',
                            ),
                            array(
                                'name' => 'parent_name',
                                'label' => 'LBL_LIST_RELATED_TO',
                                'dynamic_module' => 'PARENT_TYPE',
                                'id' => 'PARENT_ID',
                                'link' => true,
                                'enabled' => true,
                                'default' => true,
                                'sortable' => false,
                                'ACLTag' => 'PARENT',
                                'related_fields' => array(
                                    0 => 'parent_id',
                                    1 => 'parent_type',
                                ),
                            ),
                            array(
                                'name' => 'description',
                                'label' => 'LBL_DESCRIPTION',
                                'enabled' => true,
                                'sortable' => false,
                                'default' => true,
                                'width' => 'large',
                            ),
                            array(
                                'name' => 'date_start',
                                'label' => 'LBL_LIST_DATE',
                                'type' => 'jdatetime',
                            ),
                            array(
                                'enabled' => true,
                                'default' => true,
                                'name' => 'status',
                                'type' => 'event-status',
                                'css_class' => 'full-width',
                            ),
                            array(
                                'name' => 'call_result',
                                'label' => 'LBL_CALL_RESULT',
                                'enabled' => true,
                                'default' => true,
                            ),
                            array(
                                'name' => 'assigned_user_name',
                                'target_record_key' => 'assigned_user_id',
                                'target_module' => 'Employees',
                                'label' => 'LBL_LIST_ASSIGNED_USER',
                                'enabled' => true,
                                'default' => true,
                                'sortable' => true,
                            ),
                            8 => array(
                                'name' => 'modified_by_name',
                                'label' => 'LBL_MODIFIED',
                                'enabled' => true,
                                'readonly' => true,
                                'id' => 'MODIFIED_USER_ID',
                                'link' => true,
                                'default' => false,
                            ),
                            9 => array(
                                'name' => 'dri_subworkflow_name',
                                'label' => 'LBL_DRI_SUBWORKFLOW',
                                'enabled' => true,
                                'id' => 'DRI_SUBWORKFLOW_ID',
                                'link' => true,
                                'sortable' => false,
                                'default' => false,
                            ),
                            11 => array(
                                'name' => 'recall',
                                'label' => 'LBL_RECALL',
                                'enabled' => true,
                                'default' => false,
                            ),
                            14 => array(
                                'enabled' => true,
                                'default' => false,
                                'name' => 'direction',
                            ),
                            15 => array(
                                'name' => 'cj_activity_tpl_name',
                                'label' => 'LBL_DRI_WORKFLOW_TASK_TEMPLATE',
                                'enabled' => true,
                                'id' => 'DRI_WORKFLOW_TASK_TEMPLATE_ID',
                                'link' => true,
                                'sortable' => false,
                                'default' => false,
                            ),
                            16 => array(
                                'name' => 'date_entered',
                                'enabled' => true,
                                'default' => false,
                                'readonly' => true,
                            ),
                            18 => array(
                                'name' => 'dri_subworkflow_template_name',
                                'label' => 'LBL_DRI_SUBWORKFLOW_TEMPLATE',
                                'enabled' => true,
                                'id' => 'DRI_SUBWORKFLOW_TEMPLATE_ID',
                                'link' => true,
                                'sortable' => false,
                                'default' => false,
                            ),
                            19 => array(
                                'name' => 'cj_url',
                                'label' => 'LBL_CJ_URL',
                                'enabled' => true,
                                'default' => false,
                            ),
                            20 => array(
                                'name' => 'dri_workflow_template_name',
                                'label' => 'LBL_DRI_WORKFLOW_TEMPLATE',
                                'enabled' => true,
                                'id' => 'DRI_WORKFLOW_TEMPLATE_ID',
                                'link' => true,
                                'sortable' => false,
                                'default' => false,
                            ),
                            21 => array(
                                'name' => 'date_modified',
                                'label' => 'LBL_DATE_MODIFIED',
                                'enabled' => true,
                                'readonly' => true,
                                'default' => false,
                            ),
                            22 => array(
                                'name' => 'cj_momentum_end_date',
                                'label' => 'LBL_CJ_MOMENTUM_END_DATE',
                                'enabled' => true,
                                'default' => false,
                            ),
                            23 => array(
                                'name' => 'cj_momentum_start_date',
                                'label' => 'LBL_CJ_MOMENTUM_START_DATE',
                                'enabled' => true,
                                'default' => false,
                            ),
                            24 => array(
                                'name' => 'is_customer_journey_activity',
                                'label' => 'LBL_IS_CUSTOMER_JOURNEY_ACTIVITY',
                                'enabled' => true,
                                'default' => false,
                            ),
                            25 => array(
                                'name' => 'is_cj_parent_activity',
                                'label' => 'LBL_IS_CJ_PARENT_ACTIVITY',
                                'enabled' => true,
                                'default' => false,
                            ),
                            26 => array(
                                'name' => 'customer_journey_blocked_by',
                                'label' => 'LBL_CUSTOMER_JOURNEY_BLOCKED_BY',
                                'enabled' => true,
                                'default' => false,
                            ),
                            27 => array(
                                'name' => 'cj_parent_activity_type',
                                'label' => 'LBL_CJ_PARENT_ACTIVITY_TYPE',
                                'enabled' => true,
                                'default' => false,
                            ),
                            28 => array(
                                'name' => 'customer_journey_points',
                                'label' => 'LBL_CUSTOMER_JOURNEY_POINTS',
                                'enabled' => true,
                                'default' => false,
                            ),
                            29 => array(
                                'name' => 'cj_momentum_ratio',
                                'label' => 'LBL_CJ_MOMENTUM_RATIO',
                                'enabled' => true,
                                'readonly' => true,
                                'default' => false,
                            ),
                            30 => array(
                                'name' => 'customer_journey_progress',
                                'label' => 'LBL_CUSTOMER_JOURNEY_PROGRESS',
                                'enabled' => true,
                                'readonly' => true,
                                'default' => false,
                            ),
                            31 => array(
                                'name' => 'cj_momentum_score',
                                'label' => 'LBL_CJ_MOMENTUM_SCORE',
                                'enabled' => true,
                                'readonly' => true,
                                'default' => false,
                            ),
                            32 => array(
                                'name' => 'cj_momentum_points',
                                'label' => 'LBL_CJ_MOMENTUM_POINTS',
                                'enabled' => true,
                                'readonly' => true,
                                'default' => false,
                            ),
                            33 => array(
                                'name' => 'customer_journey_score',
                                'label' => 'LBL_CUSTOMER_JOURNEY_SCORE',
                                'enabled' => true,
                                'readonly' => true,
                                'default' => false,
                            ),
                            34 => array(
                                'name' => 'cj_actual_sort_order',
                                'label' => 'LBL_CJ_ACTUAL_SORT_ORDER',
                                'enabled' => true,
                                'default' => false,
                            ),
                            35 => array(
                                'name' => 'dri_workflow_sort_order',
                                'label' => 'LBL_DRI_WORKFLOW_SORT_ORDER',
                                'enabled' => true,
                                'default' => false,
                            ),
                            37 => array(
                                'name' => 'team_name',
                                'label' => 'LBL_TEAMS',
                                'enabled' => true,
                                'id' => 'TEAM_ID',
                                'link' => true,
                                'sortable' => false,
                                'default' => false,
                            ),
                            38 => array(
                                'name' => 'tag',
                                'label' => 'LBL_TAGS',
                                'enabled' => true,
                                'default' => false,
                            ),
                            39 => array(
                                'name' => 'auto_invite_parent',
                                'label' => 'auto_invite_parent',
                                'enabled' => true,
                                'default' => false,
                            ),
                            40 => array(
                                'name' => 'set_accept_links',
                                'label' => 'LBL_ACCEPT_LINK',
                                'enabled' => true,
                                'default' => false,
                            ),
                            41 => array(
                                'name' => 'accept_status',
                                'label' => 'LBL_ACCEPT_STATUS',
                                'enabled' => true,
                                'default' => false,
                            ),
                            42 => array(
                                'name' => 'parent_type',
                                'label' => 'LBL_PARENT_TYPE',
                                'enabled' => true,
                                'default' => false,
                            ),
                            43 => array(
                                'name' => 'move_trash',
                                'label' => 'LBL_MOVE_TRASH',
                                'enabled' => true,
                                'default' => false,
                            ),
                            44 => array(
                                'name' => 'mark_favorite',
                                'label' => 'LBL_MARK_FAVORITE',
                                'enabled' => true,
                                'default' => false,
                            ),
                            45 => array(
                                'name' => 'call_entrysource',
                                'label' => 'LBL_CALL_ENTRYSOURCE',
                                'enabled' => true,
                                'default' => false,
                            ),
                            46 => array(
                                'name' => 'call_recording',
                                'label' => 'LBL_CALL_RECORDING',
                                'enabled' => true,
                                'readonly' => true,
                                'default' => false,
                            ),
                            47 => array(
                                'name' => 'call_destination',
                                'label' => 'LBL_CALL_DESTINATION',
                                'enabled' => true,
                                'default' => false,
                            ),
                            48 => array(
                                'name' => 'call_source',
                                'label' => 'LBL_CALL_SOURCE',
                                'enabled' => true,
                                'default' => false,
                            ),
                            49 => array(
                                'name' => 'call_duration',
                                'label' => 'LBL_CALL_DURATION',
                                'enabled' => true,
                                'default' => false,
                            ),
                            50 => array(
                                'name' => 'created_by_name',
                                'label' => 'LBL_CREATED',
                                'enabled' => true,
                                'readonly' => true,
                                'id' => 'CREATED_BY',
                                'link' => true,
                                'default' => false,
                            ),
                            51 => array(
                                'name' => 'reminder_time',
                                'label' => 'LBL_POPUP_REMINDER_TIME',
                                'enabled' => true,
                                'default' => false,
                            ),
                            52 => array(
                                'name' => 'email_reminder_time',
                                'label' => 'LBL_EMAIL_REMINDER_TIME',
                                'enabled' => true,
                                'default' => false,
                            ),
                            53 => array(
                                'name' => 'send_invites',
                                'label' => 'LBL_SEND_INVITES',
                                'enabled' => true,
                                'default' => false,
                            ),
                            54 => array(
                                'name' => 'date_end',
                                'link' => false,
                                'default' => false,
                                'enabled' => true,
                            ),
                            55 => array(
                                'name' => 'task_related_completed',
                                'default' => false,
                                'enabled' => true,
                            ),
                        ),
                    ),
                ),
            ),
        ),
    ),
);
