<?php



$dictionary['J_Voucher'] = array(
    'table' => 'j_voucher',
    'audited' => true,
    'activity_enabled' => false,
    'duplicate_merge' => true,
    'fields' => array (
        'status' =>
        array (
            'required' => false,
            'name' => 'status',
            'vname' => 'LBL_STATUS',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => 'Inactive',
            'comments' => '',
            'help' => 'Type',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 10,
            'size' => '20',
            'options' => 'voucher_status_dom',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'discount_amount' =>
        array (
            'required' => false,
            'name' => 'discount_amount',
            'vname' => 'LBL_DISCOUNT_AMOUNT',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => 'Discount Amount',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 26,
            'size' => '20',
            'enable_range_search' => true,
            'precision' => 6,
            'default' => '',
            'related_fields' =>
                array (
                    0 => 'currency_id',
                    1 => 'base_rate',
                ),
        ),
        'discount_percent' =>
        array (
            'required' => false,
            'name' => 'discount_percent',
            'vname' => 'LBL_DISCOUNT_PERCENT',
            'dbType' => 'currency',
            'type' => 'discount',
            'massupdate' => 0,
            'comments' => '',
            'help' => 'Discount Percent',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '26',
            'size' => '20',
            'enable_range_search' => false,
            'precision' => '6',
            'default' => '',
            'related_fields' =>
                array (
                    0 => 'currency_id',
                    1 => 'base_rate',
                ),
            'symbol' => false
        ),
        'start_date' =>
        array (
            'required' => false,
            'name' => 'start_date',
            'vname' => 'LBL_START_DATE',
            'type' => 'date',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'Start Study',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
            'display_default' => 'now',
        ),
        'end_date' =>
        array (
            'required' => true,
            'name' => 'end_date',
            'vname' => 'LBL_END_DATE',
            'type' => 'date',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'End Study',
            'importable' => 'required',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
        ),
        'use_time' =>
        array (
            'required' => false,
            'name' => 'use_time',
            'vname' => 'LBL_USE_TIME',
            'type' => 'int',
            'massupdate' => 0,
            'default' => '',
            'no_default' => false,
            'comments' => '',
            'help' => 'FOC Type',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 5,
            'size' => '5',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'used_time' =>
        array (
            'required' => false,
            'name' => 'used_time',
            'vname' => 'LBL_USED_TIME',
            'type' => 'int',
            'len' => 5,
            'size' => '5',
            'default' => 0,
        ),
        'redempt_time' =>
        array (
            'required' => false,
            'name' => 'redempt_time',
            'vname' => 'LBL_REDEMPT_TIME',
            'type' => 'int',
            'len' => 5,
            'size' => '5',
            'default' => 0,
        ),
        'amount_per_used' =>
        array (
            'required' => false,
            'name' => 'amount_per_used',
            'vname' => 'LBL_AMOUNT_PER_USED',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => 'Amount Referal',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 26,
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'numeric_range_search_dom',
            'precision' => 6,
            'default' => '',
        ),
        'foc_type' =>
        array (
            'required' => true,
            'name' => 'foc_type',
            'vname' => 'LBL_FOC_TYPE',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => '',
            'no_default' => false,
            'comments' => '',
            'help' => 'FOC Type',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 30,
            'size' => '20',
            'options' => 'foc_type_payment_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        //Custom Relationship . Student  - Voucher (1-1)
        'ju_contacts' => array(
            'name'          => 'ju_contacts',
            'type'          => 'link',
            'relationship'  => 'contact_vouchers',
            'module'        => 'Contacts',
            'bean_name'     => 'Contact',
            'source'        => 'non-db',
            'vname'         => 'LBL_STUDENT_NAME',
        ),
        //Custom Relationship. Student  - Voucher (1-1)
        //Custom Relationship. Voucher - Sponsor
        'ju_sponsor'=>array(
            'name' => 'ju_sponsor',
            'type' => 'link',
            'relationship' => 'j_sponsor_vouchers',
            'module' => 'J_Sponsor',
            'bean_name' => 'J_Sponsor',
            'source' => 'non-db',
            'vname' => 'LBL_SPONSOR',
        ),
    ),
    'indices' => array (
        array(
            'name' => 'idx_name_status_del',
            'type' => 'index',
            'fields'=> array('name', 'status', 'deleted'),
        ),
        array(
            'name' => 'idx_name_status_foc_del',
            'type' => 'index',
            'fields'=> array('name', 'status', 'foc_type', 'deleted'),
        ),
    ),
    'relationships' => array (
        //Custom Relationship. Voucher - Sponsor
        'j_sponsor_vouchers' => array(
            'lhs_module'        => 'J_Voucher',
            'lhs_table'            => 'j_voucher',
            'lhs_key'            => 'id',
            'rhs_module'        => 'J_Sponsor',
            'rhs_table'            => 'j_sponsor',
            'rhs_key'            => 'voucher_id',
            'relationship_type'    => 'one-to-many',
        ),

        'contact_vouchers' => array(
            'lhs_module'        => 'J_Voucher',
            'lhs_table'            => 'j_voucher',
            'lhs_key'            => 'id',
            'rhs_module'        => 'Contacts',
            'rhs_table'            => 'contacts',
            'rhs_key'            => 'voucher_id',
            'relationship_type'    => 'one-to-one',
        ),
    ),
    'optimistic_locking' => true,
    'unified_search' => true,
    'full_text_search' => true,
);

if (!class_exists('VardefManager')){
}
VardefManager::createVardef('J_Voucher','J_Voucher', array('basic','team_security','assignable','taggable','currency'));
