<?php



$dictionary['J_Sponsor'] = array(
    'table' => 'j_sponsor',
    'audited' => true,
    'activity_enabled' => false,
    'duplicate_merge' => true,
    'fields' => array (
        'total_down' =>
        array (
            'required' => false,
            'name' => 'total_down',
            'vname' => 'LBL_DISCOUNT_SPONSOR_DOWN',
            'type' => 'currency',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 26,
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'numeric_range_search_dom',
            'precision' => 6,
        ),
        'loyalty_points' =>
        array (
            'required' => false,
            'name' => 'loyalty_points',
            'vname' => 'LBL_LOYALTY_POINTS',
            'type' => 'int',
            'len' => '50',
            'size' => '20',
            'disable_num_format' => true,
        ),
        'type' =>
        array (
            'required' => false,
            'name' => 'type',
            'vname' => 'LBL_TYPE',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => '',
            'no_default' => false,
            'comments' => '',
            'help' => 'FOC Type',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 30,
            'size' => '20',
            'options' => 'type_j_sponsor_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'foc_type' =>
        array (
            'required' => false,
            'name' => 'foc_type',
            'vname' => 'LBL_FOC_TYPE',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => '',
            'no_default' => false,
            'comments' => '',
            'help' => 'FOC Type',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 30,
            'size' => '20',
            'options' => 'foc_type_payment_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'is_owner' =>
        array (
            'name' => 'is_owner',
            'vname' => 'LBL_IS_OWNER',
            'type' => 'bool',
            'default' => '0',
        ),
        'percent' =>
        array (
            'required' => false,
            'name' => 'percent',
            'vname' => 'LBL_PERCENT',
            'type' => 'currency',
            'len' => 26,
            'precision' => 6,
            'symbol' => false
        ),
        'amount' =>
        array (
            'required' => false,
            'name' => 'amount',
            'vname' => 'LBL_AMOUNT',
            'type' => 'currency',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 26,
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'numeric_range_search_dom',
            'precision' => 6,
        ),

        'sponsor_number' =>
        array (
            'required' => false,
            'name' => 'sponsor_number',
            'vname' => 'LBL_SPONSOR_NUMBER',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'Sponsor Number',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '50',
            'size' => '20',
        ),
        'campaign_code' =>
        array (
            'required' => false,
            'name' => 'campaign_code',
            'vname' => 'LBL_CAMPAIGN_CODE',
            'type' => 'varchar',
            'len' => '50',
            'size' => '20',
        ),
        //CUSTOM RELATIONSHIP:
        //Custom Relationship. Voucher  - J_Sponsor (1-n)  By Lap Nguyen
        'voucher_code' => array(
            'required'  => false,
            'source'    => 'non-db',
            'name'      => 'voucher_code',
            'vname'     => 'LBL_VOUCHER_CODE',
            'type'      => 'relate',
            'rname'     => 'name',
            'id_name'   => 'voucher_id',
            'join_name' => 'J_Voucher',
            'link'      => 'ju_voucher',
            'table'     => 'j_voucher',
            'isnull'    => 'true',
            'module'    => 'J_Voucher',
        ),

        'voucher_id' => array(
            'name'              => 'voucher_id',
            'rname'             => 'id',
            'vname'             => 'LBL_VOUCHER_CODE',
            'type'              => 'id',
            'table'             => 'j_voucher',
            'isnull'            => 'true',
            'module'            => 'J_Voucher',
            'dbType'            => 'id',
            'reportable'        => false,
            'massupdate'        => false,
            'duplicate_merge'   => 'disabled',
        ),

        'ju_voucher' => array(
            'name'          => 'ju_voucher',
            'type'          => 'link',
            'relationship'  => 'j_sponsor_vouchers',
            'module'        => 'J_Voucher',
            'bean_name'     => 'J_Voucher',
            'source'        => 'non-db',
            'vname'         => 'LBL_VOUCHER_CODE',
        ),
        //Custom Relationship. Discount  - J_Sponsor (1-n)  By Lap Nguyen
        'discount_name' => array(
            'required'  => false,
            'source'    => 'non-db',
            'name'      => 'discount_name',
            'vname'     => 'LBL_DISCOUNT_NAME',
            'type'      => 'relate',
            'rname'     => 'name',
            'id_name'   => 'discount_id',
            'join_name' => 'J_Discount',
            'link'      => 'j_discounts',
            'table'     => 'j_discount',
            'isnull'    => 'true',
            'module'    => 'J_Discount',
        ),

        'discount_id' => array(
            'name'              => 'discount_id',
            'rname'             => 'id',
            'vname'             => 'LBL_DISCOUNT_NAME',
            'type'              => 'id',
            'table'             => 'j_discount',
            'isnull'            => 'true',
            'module'            => 'J_Discount',
            'dbType'            => 'id',
            'reportable'        => false,
            'massupdate'        => false,
            'duplicate_merge'   => 'disabled',
        ),

        'j_discounts' => array(
            'name'          => 'j_discounts',
            'type'          => 'link',
            'relationship'  => 'j_sponsor_j_discounts',
            'module'        => 'J_Discount',
            'bean_name'     => 'J_Discount',
            'source'        => 'non-db',
            'vname'         => 'LBL_DISCOUNT_NAME',
        ),
    ),
    'relationships' => array (
    ),
    'optimistic_locking' => true,
    'unified_search' => true,
    'full_text_search' => true,
);

if (!class_exists('VardefManager')){
}
VardefManager::createVardef('J_Sponsor','J_Sponsor', array('basic','team_security','assignable','taggable'));
