<?php


/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN pmse_BpmActivityStep
 */
class pmse_BpmActivityStep_dotb extends Basic {
	var $new_schema = true;
	var $module_dir = 'pmse_Project/pmse_BpmActivityStep';
    public $module_name = 'pmse_BpmActivityStep';
	var $object_name = 'pmse_BpmActivityStep';
	var $table_name = 'pmse_bpm_activity_step';
	var $importable = false;
	var $disable_custom_fields = true;
        var $id;
		var $name;
		var $date_entered;
		var $date_modified;
		var $modified_user_id;
		var $modified_by_name;
		var $created_by;
		var $created_by_name;
		var $description;
		var $deleted;
		var $created_by_link;
		var $modified_user_link;
		var $activities;
		var $assigned_user_id;
		var $assigned_user_name;
		var $assigned_user_link;
    var $pro_id;
    var $act_step_type;
    var $act_criteria;
    var $act_step_form;
    var $act_step_script;


	public function __construct(){
		parent::__construct();
	}
}

