<?php

/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN B_Invoices
 */


class B_Invoices_dotb extends Basic {
    public $new_schema = true;
    public $module_dir = 'B_Invoices';
    public $object_name = 'B_Invoices';
    public $table_name = 'b_invoices';
    public $importable = true;
    public $team_id;
    public $team_set_id;
    public $acl_team_set_id;
    public $team_count;
    public $team_name;
    public $acl_team_names;
    public $team_link;
    public $team_count_link;
    public $teams;
    public $assigned_user_id;
    public $assigned_user_name;
    public $assigned_user_link;
    public $tag;
    public $tag_link;
    public $id;
    public $name;
    public $date_entered;
    public $date_modified;
    public $modified_user_id;
    public $modified_by_name;
    public $created_by;
    public $created_by_name;
    public $description;
    public $deleted;
    public $created_by_link;
    public $modified_user_link;
    public $activities;
    public $following;
    public $following_link;
    public $my_favorite;
    public $favorite_link;
    public $locked_fields;
    public $locked_fields_link;
    public $inv_sent;
    public $invoice_type;
    public $invoice_date;
    public $due_date;
    public $po_number;
    public $status;
    public $sub_total;
    public $total;
    public $total_tax;
    public $total_paid;
    public $balance_due;
    public $ehd_id;
    public $ehd_url;
    
    public function bean_implements($interface){
        switch($interface){
            case 'ACL': return true;
        }
        return false;
    }
    
}