<?php
$dictionary['J_Discount'] = array(
    'table' => 'j_discount',
    'audited' => true,
    'activity_enabled' => false,
    'duplicate_merge' => true,
    'fields' => array (
        'ext_invoice_content' =>
        array (
            'required' => false,
            'name' => 'ext_invoice_content',
            'vname' => 'LBL_EXT_INVOICE_CONTENT',
            'type' => 'varchar',
        ),
        'start_date' =>
        array (
            'required' => true,
            'name' => 'start_date',
            'vname' => 'LBL_START_DATE',
            'type' => 'date',
            'massupdate' => 1,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'size' => '20',
            'enable_range_search' => false,
            'validation' => array('type' => 'isbefore', 'compareto' => 'end_date', 'blank' => false),
        ),
        'end_date' =>
        array (
            'required' => true,
            'name' => 'end_date',
            'vname' => 'LBL_END_DATE',
            'type' => 'date',
            'massupdate' => 1,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'size' => '20',
            'enable_range_search' => false,
        ),
        'status' =>
        array (
            'required' => false,
            'name' => 'status',
            'vname' => 'LBL_STATUS',
            'type' => 'enum',
            'massupdate' => 1,
            'default' => 'Active',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 100,
            'size' => '20',
            'options' => 'status_discount_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'type' =>
        array (
            'required' => true,
            'name' => 'type',
            'vname' => 'LBL_TYPE',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => 'Other',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 100,
            'size' => '20',
            'options' => 'type_discount_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'apply_for' =>
        array (
            'required' => false,
            'name' => 'apply_for',
            'vname' => 'LBL_APPLY_FOR',
            'type' => 'enum',
            'massupdate' => 1,
            'default' => 'Current Student',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 100,
            'size' => '20',
            'options' => 'applyfor_discount_list',
            'studio' => 'visible',
            'dependency' => false,
            'massupdate' => false,
        ),
        'policy' =>
        array (
            'required' => false,
            'name' => 'policy',
            'vname' => 'LBL_POLICY',
            'type' => 'text',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'size' => '20',
            'studio' => 'visible',
            'rows' => '4',
            'cols' => '20',
        ),
        // 'discount_percent' =>
        // array (
        //     'required' => false,
        //     'name' => 'discount_percent',
        //     'vname' => 'LBL_DISCOUNT_PERCENT',
        //     'type' => 'currency',
        //     'massupdate' => 0,
        //     'no_default' => false,
        //     'comments' => '',
        //     'help' => '',
        //     'importable' => 'true',
        //     'duplicate_merge' => 'disabled',
        //     'duplicate_merge_dom_value' => '0',
        //     'audited' => false,
        //     'reportable' => true,
        //     'unified_search' => false,
        //     'merge_filter' => 'disabled',
        //     'calculated' => false,
        //     'len' => '26',
        //     'size' => '20',
        //     'enable_range_search' => false,
        //     'precision' => '6',
        //     'symbol' => false
        // ),
        'maximum_discount_percent' =>
        array (
            'required' => false,
            'name' => 'maximum_discount_percent',
            'vname' => 'LBL_MAXIMUM_DISCOUNT_PERCENT',
            'type' => 'currency',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '26',
            'size' => '20',
            'enable_range_search' => false,
            'precision' => '6',
            'symbol' => false
        ),
        'discount_amount' =>
        array (
            'required' => false,
            'name' => 'discount_amount',
            'vname' => 'LBL_DISCOUNT_AMOUNT',
            'type' => 'currency',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '26',
            'size' => '20',
            'enable_range_search' => false,
            'precision' => '6',
        ),
        'content' =>
        array (
            'required' => false,
            'name' => 'content',
            'vname' => 'LBL_CONTENT',
            'type' => 'text',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'size' => '20',
            'studio' => 'visible',
            'rows' => '4',
            'cols' => '20',
        ),
        'course' => //Giu lai discount nay
        array (
            'required' => false,
            'name' => 'course',
            'vname' => 'LBL_COURSE',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => '',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 10,
            'size' => '20',
            'options' => 'course_discount_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'category' =>
        array (
            'required' => true,
            'name' => 'category',
            'vname' => 'LBL_CATEGORY',
            'type' => 'enum',
            'massupdate' => 1,
            'default' => '',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 150,
            'size' => '20',
            'options' => 'category_discount_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'order_no' =>
        array (
            'required'  => false,
            'name'      => 'order_no',
            'vname'     => 'LBL_ORDER',
            'type'      => 'int',
            'no_default' => false,
            'len'       => '10',
        ),
        'partnership' =>
        array (
            'required' => false,
            'name' => 'partnership',
            'vname' => 'LBL_PARTNERSHIP',
            'type' => 'text',
            'studio' => 'visible',
            'source' => 'non-db',
        ),
        'disable_list' =>
        array (
            'name' => 'disable_list',
            'vname' => 'LBL_DISABLE_LIST',
            'type' => 'text',
        ),
        'is_dis_to_inv' =>
        array (
            'name' => 'is_dis_to_inv',
            'vname' => 'LBL_IS_DIS_TO_INV',
            'type' => 'bool',
            'default' => '0',
        ),
        'is_trade_discount' =>
        array (
            'name' => 'is_trade_discount',
            'vname' => 'LBL_IS_TRADE_DISCOUNT', //Áp dụng chain discount
            'type' => 'bool',
            'default' => '0',
        ),
        'is_auto_set' =>
        array (
            'name' => 'is_auto_set',
            'vname' => 'LBL_IS_AUTO_SET', //Discount tu dong tinh toan
            'type' => 'bool',
            'default' => '0',
            'massupdate' => false,
        ),
        'is_chain_discount' =>
        array (
            'name' => 'is_chain_discount',
            'vname' => 'LBL_IS_CHAIN_DISCOUNT', //Áp dụng chain discount
            'type' => 'bool',
            'default' => '0',
        ),
        'is_accumulate' =>
        array (
            'name' => 'is_accumulate',
            'vname' => 'LBL_LOYALTY_REWARD', //Áp dụng loyalty
            'type' => 'bool',
            'default' => '1',
        ),
        //Custom Relationship JUNIOR. J_Sponsor - Discount  By Lap Nguyen
        'j_sponsor'=>array(
            'name' => 'j_sponsor',
            'type' => 'link',
            'relationship' => 'j_sponsor_j_discounts',
            'module' => 'J_Discount',
            'bean_name' => 'J_Discount',
            'source' => 'non-db',
            'vname' => 'LBL_SPONSOR_NAME',
        ),

        //None-DB Fields
        'discount_schema' => array (
            'name'      => 'discount_schema',
            'vname'     => 'LBL_DISCOUNT_SCHEMA',
            'type'      => 'multienum',
            'function' => 'getdiscount',
            'source' => 'non-db',
            'studio'    => 'visible',
            'massupdate' => 0,
        ),
        //END: None-DB Fields
    ),
    'relationships' => array (
        //Custom Relationship JUNIOR. J_Sponsor - Discount  By Lap Nguyen
        'j_sponsor_j_discounts' => array(
            'lhs_module'        => 'J_Discount',
            'lhs_table'            => 'j_discount',
            'lhs_key'            => 'id',
            'rhs_module'        => 'J_Sponsor',
            'rhs_table'            => 'j_sponsor',
            'rhs_key'            => 'discount_id',
            'relationship_type'    => 'one-to-many',
        ),
    ),
    'optimistic_locking' => true,
    'unified_search' => true,
    'full_text_search' => true,
);

if (!class_exists('VardefManager')){
}
VardefManager::createVardef('J_Discount','J_Discount', array('basic','team_security','assignable','taggable'));
