<?php


$config["languages"]=array (
  'bg_BG' => 'Български',
  'cs_CZ' => 'Česky',
  'da_DK' => 'Dansk',
  'de_DE' => 'Deutsch',
  'el_EL' => 'Ελληνικά',
  'es_ES' => 'Español',
  'fr_FR' => 'Français',
  'he_IL' => 'עברית',
  'hu_HU' => 'Magyar',
  'hr_HR' => 'Hrvatski',
  'it_it' => 'Italiano',
  'lt_LT' => 'Lietuvių',
  'ja_JP' => '日本語',
  'ko_KR' => '한국어',
  'lv_LV' => 'Latviešu',
  'nb_NO' => 'Norsk',
  'nl_NL' => 'Nederlands',
  'pl_PL' => 'Polski',
  'pt_PT' => 'Português',
  'ro_RO' => 'Română',
  'ru_RU' => 'Русский',
  'sv_SE' => 'Svenska',
  'th_TH' => 'ไทย',
  'tr_TR' => 'Türkçe',
  'zh_TW' => '繁體中文',
  'zh_CN' => '简体中文',
  'pt_BR' => 'Português Brasileiro',
  'ca_ES' => 'Català',
  'en_UK' => 'English (UK)',
  'sr_RS' => 'Српски',
  'sk_SK' => 'Slovenčina',
  'sq_AL' => 'Shqip',
  'et_EE' => 'Eesti',
  'es_LA' => 'Español (Latinoamérica)',
  'fi_FI' => 'Suomi',
  'ar_SA' => 'العربية',
  'uk_UA' => 'Українська',
);