<?php
    $dictionary['J_Payment'] = array(
        'table' => 'j_payment',
        'audited' => true,
        'activity_enabled' => false,
        'duplicate_merge' => true,
        'fields' => array (
            // ******** TASK IMPORT ***********************
            //field to change payment to balance
            //relationship with unit
            'site_id' => array(
                'name' => 'site_id',
                'vname' => 'LBL_SITE_ID',
                'type' => 'id',
                'required'=>true,
                'reportable'=>false,
                'comment' => '',
                'default'=> ''
            ),

            'site_name' => array(
                'name' => 'site_name',
                'rname' => 'name',
                'id_name' => 'site_id',
                'vname' => 'LBL_SITE_NAME',
                'type' => 'relate',
                'link' => 'site_link',
                'table' => 'c_sitedeployment',
                'isnull' => 'true',
                'module' => 'C_SiteDeployment',
                'dbType' => 'varchar',
                'len' => 'id',
                'reportable'=>true,
                'source' => 'non-db',
                'auto_populate' => true,
            ),
            'site_link' => array(
                'name' => 'site_link',
                'type' => 'link',
                'relationship' => 'payment_sitedeployment',
                'link_type' => 'one',
                'side' => 'right',
                'source' => 'non-db',
                'vname' => 'LBL_SITE_NAME',
                'id_name' => 'site_id',
            ),
            ///
            'unit_id' => array(
                'name' => 'unit_id',
                'vname' => 'LBL_UNIT_ID',
                'type' => 'id',
                'required'=>true,
                'reportable'=>false,
                'comment' => '',
                'default'=> ''
            ),

            'unit_name' => array(
                'name' => 'unit_name',
                'rname' => 'name',
                'id_name' => 'unit_id',
                'vname' => 'LBL_UNIT',
                'type' => 'relate',
                'link' => 'unit_link',
                'table' => 'j_unit',
                'isnull' => 'true',
                'module' => 'J_Unit',
                'dbType' => 'varchar',
                'len' => 'id',
                'reportable'=>true,
                'source' => 'non-db',
                'auto_populate' => true,
            ),
            'unit_link' => array(
                'name' => 'unit_link',
                'type' => 'link',
                'relationship' => 'payment_unit',
                'link_type' => 'one',
                'side' => 'right',
                'source' => 'non-db',
                'vname' => 'LBL_UNIT',
                'id_name' => 'unit_id',
            ),
            //relationship with order
            'order_id' => array(
                'name' => 'order_id',
                'vname' => 'LBL_ORDER_ID',
                'type' => 'id',
                'required'=>true,
                'reportable'=>false,
                'comment' => '',
                'default'=> ''
            ),

            'order_name' => array(
                'name' => 'order_name',
                'rname' => 'name',
                'id_name' => 'order_id',
                'vname' => 'LBL_ORDER_NAME',
                'type' => 'relate',
                'link' => 'order_link',
                'table' => 'quotes',
                'isnull' => 'true',
                'module' => 'Quotes',
                'dbType' => 'varchar',
                'len' => 'id',
                'reportable'=>true,
                'source' => 'non-db',
                'auto_populate' => true,
            ),
            'order_link' => array(
                'name' => 'order_link',
                'type' => 'link',
                'relationship' => 'order_create_payment',
                'link_type' => 'one',
                'side' => 'right',
                'source' => 'non-db',
                'vname' => 'LBL_ORDER_NAME',
                'id_name' => 'order_id',
            ),

            //relationship with receipt
            'receipt_id' => array(
                'name' => 'receipt_id',
                'vname' => 'LBL_RECEIPT_ID',
                'type' => 'id',
                'required'=>true,
                'reportable'=>false,
                'comment' => '',
                'default'=> ''
            ),

            'receipt_name' => array(
                'name' => 'receipt_name',
                'rname' => 'name',
                'id_name' => 'receipt_id',
                'vname' => 'LBL_RECEIPT_NAME',
                'type' => 'relate',
                'link' => 'receipt_link',
                'table' => 'j_paymentdetail',
                'isnull' => 'true',
                'module' => 'J_PaymentDetail',
                'dbType' => 'varchar',
                'len' => 'id',
                'reportable'=>true,
                'source' => 'non-db',
                'auto_populate' => true,
            ),
            'receipt_link' => array(
                'name' => 'receipt_link',
                'type' => 'link',
                'relationship' => 'receipt_payment',
                'link_type' => 'one',
                'side' => 'right',
                'source' => 'non-db',
                'vname' => 'LBL_RECEIPT_NAME',
                'id_name' => 'receipt_id',
            ),
            //
            'product_id' => array(
                'name' => 'product_id',
                'vname' => 'LBL_PRODUCT_ID',
                'type' => 'id',
                'required'=>true,
                'reportable'=>false,
                'comment' => '',
                'default'=> ''
            ),

            'product_name' => array(
                'name' => 'product_name',
                'rname' => 'name',
                'id_name' => 'product_id',
                'vname' => 'LBL_PRODUCT_NAME',
                'type' => 'relate',
                'link' => 'product_link',
                'table' => 'products',
                'isnull' => 'true',
                'module' => 'Products',
                'dbType' => 'varchar',
                'len' => 'id',
                'reportable'=>true,
                'source' => 'non-db',
                'auto_populate' => true,
            ),
            'product_link' => array(
                'name' => 'product_link',
                'type' => 'link',
                'relationship' => 'payment_of_product',
                'link_type' => 'one',
                'side' => 'right',
                'source' => 'non-db',
                'vname' => 'LBL_PRODUCT_NAME',
                'id_name' => 'product_id',
            ),
            'limit_quantity' => array(
                'name' => 'limit_quantity',
                'vname' => 'LBL_LIMIT_QUANTITY',
                'type' => 'currency',
                'len' => '12',
                'precision' => '6',
                'validation' => array('type' => 'range', 'greaterthan' => -1),
                'comment' => 'Quantity can use',
                'default' => 0.0,
                'symbol' => false
            ),
            'total_quantity' => array(
                'name' => 'total_quantity',
                'vname' => 'LBL_TOTAL_QUANTITY',
                'type' => 'currency',
                'len' => '12',
                'precision' => '6',
                'validation' => array('type' => 'range', 'greaterthan' => -1),
                'comment' => 'Quantity can use',
                'default' => 0.0,
                'symbol' => false
            ),
            'remain_quantity' => array(
                'name' => 'remain_quantity',
                'vname' => 'LBL_REMAIN_QUANTITY',
                'type' => 'currency',
                'len' => '12',
                'precision' => '6',
                'validation' => array('type' => 'range', 'greaterthan' => -1),
                'comment' => 'Quantity can use',
                'default' => 0.0,
                'symbol' => false
            ),
            ////////////////////
            'old_remain_amount' =>
            array (
                'required' => false,
                'name' => 'old_remain_amount',
                'vname' => 'Old Remain Amount (Import)',
                'type' => 'currency',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => false,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'default' => '',
                'calculated' => false,
                'len' => '26',
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 6,
            ),
            'paid_amount_import' =>
            array (
                'required' => false,
                'name' => 'paid_amount_import',
                'vname' => 'Paid Amount (Import)',
                'type' => 'currency',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'default' => '',
                'calculated' => false,
                'len' => '26',
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 6,
                'source'=>'non-db',
            ),
            'unpaid_amount_import' =>
            array (
                'required' => false,
                'name' => 'unpaid_amount_import',
                'vname' => 'Unpaid Amount (Import)',
                'type' => 'currency',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'default' => '',
                'calculated' => false,
                'len' => '26',
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 6,
                'source'=>'non-db',
            ),
            // ******** END: TASK IMPORT ***********************

            'payment_type' =>
            array (
                'required' => true,
                'name' => 'payment_type',
                'vname' => 'LBL_PAYMENT_TYPE',
                'type' => 'enum',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'default' => 'Enrollment',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'options' => 'payment_type_list',
                'dependency' => false,
            ),
            'payment_date' =>
            array (
                'required' => true,
                'name' => 'payment_date',
                'vname' => 'LBL_PAYMENT_DATE',
                'type' => 'date',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'calculated' => false,
                'size' => '20',
                'enable_range_search' => false,
                'display_default' => 'now',
            ),
            'moving_tran_out_date' =>
            array (
                'required' => true,
                'name' => 'moving_tran_out_date',
                'vname' => 'LBL_MOVING_TRAN_OUT_DATE',
                'type' => 'date',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'calculated' => false,
                'size' => '20',
                'enable_range_search' => false,
                'display_default' => 'now',
            ),
            'moving_tran_in_date' =>
            array (
                'required' => true,
                'name' => 'moving_tran_in_date',
                'vname' => 'LBL_MOVING_TRAN_IN_DATE',
                'type' => 'date',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'calculated' => false,
                'size' => '20',
                'enable_range_search' => false,
                'display_default' => 'now',
            ),
            'sale_type' =>
            array (
                'required' => false,
                'name' => 'sale_type',
                'vname' => 'LBL_SALE_TYPE',
                'type' => 'enum',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'default' => '',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'options' => 'sale_type_list',
                'dependency' => false,
            ),
            'sale_type_date' =>
            array (
                'required' => true,
                'name' => 'sale_type_date',
                'vname' => 'LBL_SALE_TYPE_DATE',
                'type' => 'date',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'calculated' => false,
                'size' => '20',
                'enable_range_search' => false,
            ),
            'start_study' =>
            array (
                'required' => true,
                'name' => 'start_study',
                'vname' => 'LBL_START_STUDY',
                'type' => 'date',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'calculated' => false,
                'size' => '20',
                'enable_range_search' => false,
            ),
            'end_study' =>
            array (
                'required' => true,
                'name' => 'end_study',
                'vname' => 'LBL_END_STUDY',
                'type' => 'date',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'calculated' => false,
                'size' => '20',
                'enable_range_search' => false,
            ),
            'tuition_fee' =>
            array (
                'required' => false,
                'name' => 'tuition_fee',
                'vname' => 'LBL_TUITION_FEE',
                'type' => 'currency',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'default' => 0.0,
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 2,
                'related_fields' =>
                array (
                    0 => 'currency_id',
                    1 => 'base_rate',
                ),
            ),
            'currency_id' =>
            array (
                'required' => false,
                'name' => 'currency_id',
                'vname' => 'LBL_CURRENCY_ID',
                'type' => 'currency_id',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'enabled',
                'duplicate_merge_dom_value' => 1,
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'calculated' => false,
                'len' => 36,
                'size' => '20',
                'dbType' => 'id',
                'studio' => false,
                'function' => 'getCurrencies',
                'function_bean' => 'Currencies',
            ),
            'base_rate' =>
            array (
                'required' => false,
                'name' => 'base_rate',
                'vname' => 'LBL_CURRENCY_RATE',
                'type' => 'decimal',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'enabled',
                'duplicate_merge_dom_value' => 1,
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 2,
                'label' => 'LBL_CURRENCY_RATE',
                'studio' => false,
            ),
            'paid_amount' =>
            array (
                'required' => false,
                'name' => 'paid_amount',
                'vname' => 'LBL_PAID_AMOUNT',
                'type' => 'currency',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'default' => 0.0,
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 6,
                'related_fields' =>
                array (
                    0 => 'currency_id',
                    1 => 'base_rate',
                ),
            ),
            'amount_bef_discount' =>
            array (
                'required' => false,
                'name' => 'amount_bef_discount',
                'vname' => 'LBL_AMOUNT_BEF_DISCOUNT',
                'type' => 'currency',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'default' => 0.0,
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 6,
                'related_fields' =>
                array (
                    0 => 'currency_id',
                    1 => 'base_rate',
                ),
            ),
            'discount_amount' =>
            array (
                'required' => false,
                'name' => 'discount_amount',
                'vname' => 'LBL_DISCOUNT_AMOUNT',
                'type' => 'currency',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'default' => 0.0,
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 6,
                'related_fields' =>
                array (
                    0 => 'currency_id',
                    1 => 'base_rate',
                ),
            ),
            'remaining_freebalace' =>
            array (
                'required' => false,
                'name' => 'remaining_freebalace',
                'vname' => 'LBL_REMAINING_FREEBALACE',
                'type' => 'currency',
                'source'=>'non-db',
                'len' => 26,
                'size' => '20',
                'precision' => 6,
            ),
            'dis_hours' =>
            array (
                'required' => false,
                'name' => 'dis_hours',
                'vname' => 'LBL_DIS_HOURS',
                'type' => 'currency',
                'len' => 13,
                'size' => '20',
                'precision' => 6,
            ),
            'discount_percent' =>
            array (
                'required' => false,
                'name' => 'discount_percent',
                'vname' => 'LBL_DISCOUNT_PERCENT',
                'type' => 'currency',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'default' => '',
                'calculated' => false,
                'len' => '26',
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 6,
                'symbol' => false
            ),
            'ratio' =>
            array (
                'required' => false,
                'name' => 'ratio',
                'vname' => 'LBL_RATIO',
                'type' => 'decimal',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'default' => '',
                'calculated' => false,
                'len' => '26',
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 6,
            ),
            'total_after_discount' =>
            array (
                'required' => false,
                'name' => 'total_after_discount',
                'vname' => 'LBL_TOTAL_AFTER_DISCOUNT',
                'type' => 'currency',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'default' => 0.0,
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 6,
                'related_fields' =>
                array (
                    0 => 'currency_id',
                    1 => 'base_rate',
                ),
            ),
            'deposit_amount' =>
            array (
                'required' => false,
                'name' => 'deposit_amount',
                'vname' => 'LBL_DEPOSIT_AMOUNT',
                'type' => 'currency',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'default' => 0.0,
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 6,
                'related_fields' =>
                array (
                    0 => 'currency_id',
                    1 => 'base_rate',
                ),
            ),
            'payment_amount' =>
            array (
                'required' => false,
                'name' => 'payment_amount',
                'vname' => 'LBL_GRAND_TOTAL',
                'type' => 'currency',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'default' => 0.0,
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 6,
            ),
            'payment_expired' =>
            array (
                'required' => true,
                'name' => 'payment_expired',
                'vname' => 'LBL_PAYMENT_EXPIRED',
                'type' => 'date',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'calculated' => false,
                'size' => '20',
                'enable_range_search' => false,
            ),
            'date_active' =>
                array (
                    'required' => true,
                    'name' => 'date_active',
                    'vname' => 'LBL_DATE_ACTIVE',
                    'dbType' => 'date',
                    'type' => 'jdate',
                    'massupdate' => false,
                    'no_default' => false,
                    'comments' => '',
                    'help' => '',
                    'importable' => 'true',
                    'duplicate_merge' => 'disabled',
                    'duplicate_merge_dom_value' => '0',
                    'audited' => true,
                    'reportable' => true,
                    'unified_search' => false,
                    'merge_filter' => 'disabled',
                    'pii' => false,
                    'calculated' => false,
                    'size' => '20',
                    'enable_range_search' => false,
                ),
            'final_sponsor' =>
            array (
                'required' => false,
                'name' => 'final_sponsor',
                'vname' => 'LBL_FINAL_SPONSOR',
                'type' => 'currency',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'default' => 0.0,
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 6,
                'related_fields' =>
                array (
                    0 => 'currency_id',
                    1 => 'base_rate',
                ),
            ),
            'final_sponsor_percent' =>
            array (
                'required' => false,
                'name' => 'final_sponsor_percent',
                'vname' => 'LBL_FINAL_SPONSOR_PERCENT',
                'type' => 'currency',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'default' => '',
                'calculated' => false,
                'len' => '26',
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 6,
                'symbol' => false
            ),
            'loyalty_amount' =>
            array (
                'required' => false,
                'name' => 'loyalty_amount',
                'vname' => 'LBL_LOYALTY_AMOUNT',
                'type' => 'currency',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'default' => 0.0,
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 6,
                'related_fields' =>
                array (
                    0 => 'currency_id',
                    1 => 'base_rate',
                ),
            ),
            'loyalty_percent' =>
            array (
                'required' => false,
                'name' => 'loyalty_percent',
                'vname' => 'LBL_LOYALTY_PERCENT',
                'type' => 'currency',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'default' => '',
                'calculated' => false,
                'len' => '26',
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 6,
                'symbol' => false
            ),
            'used_amount' =>
            array (
                'required' => false,
                'name' => 'used_amount',
                'vname' => 'LBL_USED_AMOUNT',
                'type' => 'currency',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'default' => 0.0,
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 6,
                'related_fields' =>
                array (
                    0 => 'currency_id',
                    1 => 'base_rate',
                ),
            ),
            'remain_amount' =>
            array (
                'required' => false,
                'name' => 'remain_amount',
                'vname' => 'LBL_REMAIN_AMOUNT',
                'type' => 'currency',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'default' => 0.0,
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 6,
                'related_fields' =>
                array (
                    0 => 'currency_id',
                    1 => 'base_rate',
                ),
            ),
            'payment_list' =>
            array (
                'name' => 'payment_list',
                'vname' => 'LBL_PAYMENT_LIST',
                'type' => 'text',
            ),
            'note' =>
            array (
                'required' => false,
                'name' => 'note',
                'vname' => 'LBL_NOTE',
                'type' => 'varchar',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'default' => '',
                'full_text_search' =>
                array (
                    'enabled' => '0',
                    'boost' => '1',
                    'searchable' => false,
                ),
                'calculated' => false,
                'len' => '255',
                'size' => '20',
            ),
            'outstanding_list' =>
            array (
                'name' => 'outstanding_list',
                'vname' => 'LBL_OUTSTANDING_LIST',
                'type' => 'text',
            ),
            'do_not_drop_revenue' =>
            array (
                'required' => false,
                'name' => 'do_not_drop_revenue',
                'vname' => 'LBL_DO_NOT_DROP_REVENUE',
                'type' => 'bool',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'default' => false,
                'calculated' => false,
                'size' => '20',
            ),
            'is_corporate' =>
            array (
                'required' => false,
                'name' => 'is_corporate',
                'vname' => 'LBL_IS_CORPORATE',
                'type' => 'bool',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'default' => false,
                'calculated' => false,
                'size' => '20',
            ),
            'status' =>
            array (
                'required' => false,
                'name' => 'status',
                'vname' => 'LBL_STATUS',
                'type' => 'enum',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'default' => 'Available',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'options' => 'status_payment_list',
                'dependency' => false,
            ),
            'refund_revenue' =>
            array (
                'required' => false,
                'name' => 'refund_revenue',
                'vname' => 'LBL_REFUND_REVENUE',
                'type' => 'currency',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'default' => 0.0,
                'calculated' => false,
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 2,
                'related_fields' =>
                array (
                    0 => 'currency_id',
                    1 => 'base_rate',
                ),
            ),
            'parent_type' =>
            array (
                'required' => false,
                'name' => 'parent_type',
                'vname' => 'LBL_PARENT',
                'type' => 'enum',
                'options' => 'parent_type_display',
                'massupdate' => 0,
                'default' => 'Contacts',
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '30',
                'size' => '20',
            ),
            'use_type' =>
            array (
                'required' => false,
                'name' => 'use_type',
                'vname' => 'LBL_USE_TYPE',
                'type' => 'enum',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'default' => 'Hour',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'options' => 'use_type_options',
                'dependency' => false,
            ),
            'catch_limit' =>
            array (
                'required' => false,
                'name' => 'catch_limit',
                'vname' => 'LBL_CATCH_LIMIT',
                'type' => 'bool',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'default' => false,
                'calculated' => false,
                'size' => '20',
            ),
            'is_convert' =>
            array (
                'required' => false,
                'name' => 'is_convert',
                'vname' => 'LBL_IS_CONVERT',
                'type' => 'bool',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'default' => false,
                'calculated' => false,
                'size' => '20',
            ),
            'duration_exp' =>
            array (
                'required' => false,
                'name' => 'duration_exp',
                'vname' => 'LBL_DURATION_EXP',
                'type' => 'enum',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'default' => '',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'options' => 'duration_exp_list',
                'dependency' => false,
            ),
            'af_duration_exp' =>
            array (
                'required' => false,
                'name' => 'af_duration_exp',
                'vname' => 'LBL_AF_DURATION_EXP',
                'type' => 'varchar',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'default' => '',
                'full_text_search' =>
                array (
                    'enabled' => '0',
                    'boost' => '1',
                    'searchable' => false,
                ),
                'calculated' => false,
                'len' => '255',
                'size' => '20',
            ),
            'content' =>
            array (
                'name' => 'content',
                'vname' => 'LBL_CONTENT',
                'type' => 'text',
            ),

            'is_convert' =>
            array (
                'name' => 'is_convert',
                'vname' => 'LBL_IS_CONVERT',
                'type' => 'bool',
                'default' => '0',
            ),

            //NON-DB FIELDS
            'payment_method' =>
            array (
                'required' => false,
                'name' => 'payment_method',
                'vname' => 'LBL_PAYMENT_METHOD',
                'type' => 'enum',
                'massupdate' => 0,
                'default' => 'Cash',
                'no_default' => false,
                'comments' => '',
                'help' => 'Payment Method',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 50,
                'size' => '20',
                'options' => 'payment_method_list',
                'studio' => 'visible',
                'dependency' => false,
                'source' => 'non-db',
            ),
            'card_type' =>
            array (
                'required' => false,
                'name' => 'card_type',
                'vname' => 'LBL_CARD_TYPE',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '50',
                'size' => '20',
                'source' => 'non-db',
            ),
            'related_payment_detail' =>
            array (
                'required' => false,
                'name' => 'related_payment_detail',
                'vname' => 'LBL_RELATED_PAYMENT_DETAIL',
                'type' => 'varchar',
                'len' => 5,
                'size' => '20',
                'source' => 'non-db',
            ),
            'related_payment_list' =>
            array (
                'required' => false,
                'name' => 'related_payment_list',
                'vname' => 'LBL_RELATED_PAYMENT_LIST',
                'type' => 'varchar',
                'len' => 5,
                'size' => '20',
                'source' => 'non-db',
            ),
            'phone' =>
            array (
                'required' => false,
                'name' => 'phone',
                'vname' => 'LBL_PHONE',
                'type' => 'varchar',
                'len' => 5,
                'size' => '20',
                'source' => 'non-db',
            ),

            'company_name' => array (
                'required' => false,
                'name' => 'company_name',
                'vname' => 'LBL_ACCOUNT_NAME',
                'type' => 'varchar',
                'source' => 'non-db',
                'len' => '150',
                'reportable' => true,
            ),
            'tax_code' => array (
                'required' => false,
                'name' => 'tax_code',
                'vname' => 'LBL_TAX_CODE',
                'type' => 'varchar',
                'source' => 'non-db',
                'len' => '50',
                'reportable' => true,
            ),
            'company_address' => array (
                'required' => false,
                'name' => 'company_address',
                'vname' => 'LBL_COMPANY_ADDRESS',
                'type' => 'varchar',
                'source' => 'non-db',
                'len' => '200',
                'reportable' => true,
            ),

            //BEGIN: RELATED FIELDS

            //Add Relationship Invoice - Receipt
            'invoice_id' => array(
                'name' => 'invoice_id',
                'vname' => 'LBL_INVOICE_ID',
                'type' => 'id',
                'required'=>false,
                'reportable'=>false,
                'comment' => ''
            ),

            'invoice_name' => array(
                'name' => 'invoice_name',
                'rname' => 'name',
                'id_name' => 'invoice_id',
                'vname' => 'LBL_INVOICE_ID',
                'type' => 'relate',
                'link' => 'invoice_link',
                'table' => 'j_invoice',
                'isnull' => 'true',
                'module' => 'J_Invoice',
                'dbType' => 'varchar',
                'len' => 'id',
                'reportable'=>true,
                'source' => 'non-db',
            ),

            'invoice_link' => array(
                'name' => 'invoice_link',
                'type' => 'link',
                'relationship' => 'invoice_payment',
                'link_type' => 'one',
                'side' => 'right',
                'source' => 'non-db',
                'vname' => 'LBL_INVOICE_ID',
            ),
            //  Invoice - Receipt

            //Add Relationship Account - Payment

            //Primary Payment ID
            'primary_pay_id' => array(
                'name'              => 'primary_pay_id',
                'rname'             => 'id',
                'vname'             => 'LBL_PRIMARY_PAY_ID',
                'type'              => 'id',
                'table'             => 'j_payment',
                'isnull'            => 'true',
                'module'            => 'J_Payment',
                'dbType'            => 'id',
                'reportable'        => false,
                'massupdate'        => false,
                'duplicate_merge'   => 'disabled',
            ),

            //Move to Center
//            'move_to_center_id' =>  array (
//                'required' => false,
//                'name' => 'move_to_center_id',
//                'vname' => '',
//                'type' => 'id',
//                'massupdate' => 0,
//                'comments' => '',
//                'help' => '',
//                'duplicate_merge' => 'disabled',
//                'duplicate_merge_dom_value' => 0,
//                'audited' => 0,
//                'reportable' => false,
//                'len' => 36,
//            ),
//
//            'move_to_center_name' =>  array (
//                'required' => false,
//                'source' => 'non-db',
//                'name' => 'move_to_center_name',
//                'vname' => 'LBL_MOVE_TO_CENTER_NAME',
//                'type' => 'relate',
//                'massupdate' => 0,
//                'comments' => '',
//                'help' => '',
//                'duplicate_merge' => 'disabled',
//                'duplicate_merge_dom_value' => 0,
//                'audited' => 0,
//                'reportable' => true,
//                'len' => '255',
//                'id_name' => 'move_to_center_id',
//                'ext2' => 'Teams',
//                'module' => 'Teams',
//                'studio' => 'visible',
//            ),
//
//            //Tranfer to Student
//            'transfer_to_student_id' =>  array (
//                'required' => false,
//                'name' => 'transfer_to_student_id',
//                'vname' => '',
//                'type' => 'id',
//                'massupdate' => 0,
//                'comments' => '',
//                'help' => '',
//                'duplicate_merge' => 'disabled',
//                'duplicate_merge_dom_value' => 0,
//                'audited' => 0,
//                'reportable' => false,
//                'len' => 36,
//            ),
//
//            'transfer_to_student_name' =>  array (
//                'required' => false,
//                'source' => 'non-db',
//                'name' => 'transfer_to_student_name',
//                'vname' => 'LBL_TRANSFER_TO_STUDENT_NAME',
//                'type' => 'relate',
//                'massupdate' => 0,
//                'comments' => '',
//                'help' => '',
//                'duplicate_merge' => 'disabled',
//                'duplicate_merge_dom_value' => 0,
//                'audited' => 0,
//                'reportable' => true,
//                'len' => '255',
//                'id_name' => 'transfer_to_student_id',
//                'ext2' => 'Contacts',
//                'module' => 'Contacts',
//                'studio' => 'visible',
//            ),
            //END: RELATED FIELDS

            //BEGIN: CUSTOM RELATIONSHIP FIEDLS
            //Custom Relationship JUNIOR. Payment - Carryforward
//            'c_carryforward'=>array(
//                'name' => 'c_carryforward',
//                'type' => 'link',
//                'relationship' => 'j_payment_carryforward',
//                'module' => 'C_Carryforward',
//                'bean_name' => 'C_Carryforward',
//                'source' => 'non-db',
//                'vname' => 'LBL_CARRYFORWARD',
//            ),
            //Custom Relationship. Payment - Student Situation
//            'ju_studentsituations'=>array(
//                'name' => 'ju_studentsituations',
//                'type' => 'link',
//                'relationship' => 'j_payment_studentsituations',
//                'module' => 'J_StudentSituations',
//                'bean_name' => 'J_StudentSituations',
//                'source' => 'non-db',
//                'vname' => 'LBL_STUDENT_SITUATION',
//            ),
//            //Custom Relationship. Payment - Student Situation  By Lap Nguyen
//            'ju_sponsor'=>array(
//                'name' => 'ju_sponsor',
//                'type' => 'link',
//                'relationship' => 'j_payment_j_sponsor',
//                'module' => 'J_Sponsor',
//                'bean_name' => 'J_Sponsor',
//                'source' => 'non-db',
//                'vname' => 'LBL_SPONSOR_COUNT',
//            ),
//            //Custom Relationship. Payment - Payment (Transfer In/Out)
//            // Left side
//            'ju_payment_in' => array(
//                'name'          => 'ju_payment_in',
//                'type'          => 'link',
//                'relationship'  => 'j_payment_moving_transfer',
//                'module'        => 'J_Payment',
//                'bean_name'     => 'J_Payment',
//                'source'        => 'non-db',
//                'vname'         => 'LBL_PAYMENT_IN_NAME',
//            ),
//            // Right side
//            'payment_out_name' => array(
//                'required'  => false,
//                'source'    => 'non-db',
//                'name'      => 'payment_out_name',
//                'vname'     => 'LBL_PAYMENT_OUT_NAME',
//                'type'      => 'relate',
//                'rname'     => 'name',
//                'id_name'   => 'payment_out_id',
//                'join_name' => 'payment',
//                'link'      => 'ju_payment_out',
//                'table'     => 'j_payment',
//                'isnull'    => 'true',
//                'module'    => 'J_Payment',
//            ),
//            'payment_out_id' => array(
//                'name'              => 'payment_out_id',
//                'rname'             => 'id',
//                'vname'             => 'LBL_PAYMENT_OUT_NAME',
//                'type'              => 'id',
//                'table'             => 'j_payment',
//                'isnull'            => 'true',
//                'module'            => 'J_Payment',
//                'dbType'            => 'id',
//                'reportable'        => false,
//                'massupdate'        => false,
//                'duplicate_merge'   => 'disabled',
//            ),
//            'ju_payment_out' => array(
//                'name'          => 'ju_payment_out',
//                'type'          => 'link',
//                'relationship'  => 'j_payment_moving_transfer',
//                'module'        => 'J_Payment',
//                'bean_name'     => 'J_Payment',
//                'source'        => 'non-db',
//                'vname'         => 'LBL_PAYMENT_OUT_NAME',
//            ),

            //Add Relationship Situation Delay - Payment Delay (1 - n)
            //Right Side (n)
//            'delay_situation_id' => array(
//                'name' => 'delay_situation_id',
//                'vname' => 'LBL_DELAY_SITUATION_NAME',
//                'type' => 'id',
//                'required'=>false,
//                'reportable'=>false,
//                'comment' => ''
//            ),

//            'delay_situation_name' => array(
//                'name' => 'delay_situation_name',
//                'rname' => 'name',
//                'id_name' => 'delay_situation_id',
//                'vname' => 'LBL_DELAY_SITUATION_NAME',
//                'type' => 'relate',
//                'link' => 'situation_delay_link',
//                'table' => 'j_studentsituations',
//                'isnull' => 'true',
//                'module' => 'J_StudentSituations',
//                'dbType' => 'varchar',
//                'len' => 'id',
//                'reportable'=>true,
//                'source' => 'non-db',
//            ),

//            'situation_delay_link' => array(
//                'name' => 'situation_delay_link',
//                'type' => 'link',
//                'relationship' => 'situation_delay_payment_delay',
//                'link_type' => 'one',
//                'side' => 'right',
//                'source' => 'non-db',
//                'vname' => 'LBL_DELAY_SITUATION_NAME',
//            ),
            //Add Relationship Payment - Receipt (Split Payment)
            'paymentdetail_link'=>array(
                'name' => 'paymentdetail_link',
                'type' => 'link',
                'relationship' => 'payment_paymentdetails',
                'module' => 'J_PaymentDetail',
                'bean_name' => 'J_PaymentDetail',
                'source' => 'non-db',
                'vname' => 'LBL_PAYMENT_DETAIL',
            ),
            //Add Relationship Payment - Invoice (Split Payment)
            'invoice_link'=>array(
                'name' => 'invoice_link',
                'type' => 'link',
                'relationship' => 'payment_invoices',
                'module' => 'J_Invoice',
                'bean_name' => 'J_Invoice',
                'source' => 'non-db',
                'vname' => 'LBL_INVOICE',
            ),
            //Add Relationship Payment - Loyalty
            'loyalty_link'=>array(
                'name' => 'loyalty_link',
                'type' => 'link',
                'relationship' => 'payment_loyaltys',
                'module' => 'J_Loyalty',
                'bean_name' => 'J_Loyalty',
                'source' => 'non-db',
                'vname' => 'LBL_LOYALTY',
            ),

            //Add Relationship Payment - Commission
//            'com_link'=>array(
//                'name' => 'com_link',
//                'type' => 'link',
//                'relationship' => 'payment_coms',
//                'module' => 'C_Commission',
//                'bean_name' => 'C_Commission',
//                'source' => 'non-db',
//                'vname' => 'LBL_COMMISSION',
//            ),

            //Add Relationship Lead - Payment (Placement Test / Deposit)
//            'lead_name' => array(
//                'required'  => false,
//                'source'    => 'non-db',
//                'name'      => 'lead_name',
//                'vname'     => 'LBL_LEAD_NAME',
//                'type'      => 'relate',
//                'rname'     => 'name',
//                'id_name'   => 'lead_id',
//                'join_name' => 'leads',
//                'link'      => 'lead_link',
//                'table'     => 'leads',
//                'isnull'    => 'true',
//                'module'    => 'Leads',
//            ),
//
//            'lead_id' => array(
//                'name'              => 'lead_id',
//                'rname'             => 'id',
//                'vname'             => 'LBL_LEAD_NAME',
//                'type'              => 'id',
//                'table'             => 'leads',
//                'isnull'            => 'true',
//                'module'            => 'Leads',
//                'dbType'            => 'id',
//                'reportable'        => false,
//                'massupdate'        => false,
//                'duplicate_merge'   => 'disabled',
//            ),
//
//            'lead_link' => array(
//                'name'          => 'lead_link',
//                'type'          => 'link',
//                'relationship'  => 'lead_payments',
//                'module'        => 'Leads',
//                'bean_name'     => 'Lead',
//                'source'        => 'non-db',
//                'vname'         => 'LBL_LEAD_NAME',
//            ),

            // Relationship Payment ( 1 - n ) Delivery Revenue
//            'revenue_link' =>
//            array (
//                'name' => 'revenue_link',
//                'type' => 'link',
//                'relationship' => 'ju_payment_revenue',
//                'module' => 'C_DeliveryRevenue',
//                'bean_name' => 'C_DeliveryRevenue',
//                'source' => 'non-db',
//                'vname' => 'LBL_DELIVERY_REVENUE',
//            ),
//
//            //Add Relationship Contract - Payment
//            'contract_id' => array(
//                'name' => 'contract_id',
//                'vname' => 'LBL_CONTRACT_NAME',
//                'type' => 'id',
//                'required'=>false,
//                'reportable'=>false,
//                'comment' => ''
//            ),
//
//            'contract_name' => array(
//                'name' => 'contract_name',
//                'rname' => 'name',
//                'id_name' => 'contract_id',
//                'vname' => 'LBL_CONTRACT_NAME',
//                'type' => 'relate',
//                'link' => 'contract_link',
//                'table' => 'contracts',
//                'isnull' => 'true',
//                'module' => 'Contracts',
//                'dbType' => 'varchar',
//                'len' => 'id',
//                'reportable'=>true,
//                'source' => 'non-db',
//            ),
//
//            'contract_link' => array(
//                'name' => 'contract_link',
//                'type' => 'link',
//                'relationship' => 'contract_j_payment',
//                'link_type' => 'one',
//                'side' => 'right',
//                'source' => 'non-db',
//                'vname' => 'LBL_CONTRACT_NAME',
//            ),
//
//            //Add Relationship Closed Sale By - Payment
//            'user_closed_sale_id' => array(
//                'name' => 'user_closed_sale_id',
//                'vname' => 'LBL_USER_CLOSED_SALE',
//                'type' => 'id',
//                'required'=>false,
//                'reportable'=>false,
//                'comment' => ''
//            ),
//
//            'user_closed_sale' => array(
//                'name' => 'user_closed_sale',
//                'rname' => 'name',
//                'id_name' => 'user_closed_sale_id',
//                'vname' => 'LBL_USER_CLOSED_SALE',
//                'type' => 'relate',
//                'link' => 'user_closed_sale_link',
//                'table' => 'users',
//                'isnull' => 'true',
//                'module' => 'Users',
//                'dbType' => 'varchar',
//                'len' => 'id',
//                'reportable'=>true,
//                'source' => 'non-db',
//            ),
//
//            'user_closed_sale_link' => array(
//                'name' => 'user_closed_sale_link',
//                'type' => 'link',
//                'relationship' => 'payment_user_closed_sale',
//                'link_type' => 'one',
//                'side' => 'right',
//                'source' => 'non-db',
//                'vname' => 'LBL_USER_CLOSED_SALE',
//            ),
            //Add Relationship PT/Demo - Payment
//            'user_pt_demo_id' => array(
//                'name' => 'user_pt_demo_id',
//                'vname' => 'LBL_USER_PT_DEMO',
//                'type' => 'id',
//                'required'=>false,
//                'reportable'=>false,
//                'comment' => ''
//            ),
//
//            'user_pt_demo' => array(
//                'name' => 'user_pt_demo',
//                'rname' => 'name',
//                'id_name' => 'user_pt_demo_id',
//                'vname' => 'LBL_USER_PT_DEMO',
//                'type' => 'relate',
//                'link' => 'user_pt_demo_link',
//                'table' => 'users',
//                'isnull' => 'true',
//                'module' => 'Users',
//                'dbType' => 'varchar',
//                'len' => 'id',
//                'reportable'=>true,
//                'source' => 'non-db',
//            ),
//
//            'user_pt_demo_link' => array(
//                'name' => 'user_pt_demo_link',
//                'type' => 'link',
//                'relationship' => 'payment_user_pt_demo',
//                'link_type' => 'one',
//                'side' => 'right',
//                'source' => 'non-db',
//                'vname' => 'LBL_USER_PT_DEMO',
//            ),
            //END: CUSTOM RELATIONSHIP FIEDLS

        ),
        'indices' => array (
            array(
                'name' => 'idx_primary_pay_id',
                'type' => 'index',
                'fields'=> array('primary_pay_id'),
            ),
        ),
        'relationships' => array (

            //Custom Relationship JUNIOR. Payment - CarryForward  By Lap Nguyen
            'j_payment_carryforward' => array(
                'lhs_module'        => 'J_Payment',
                'lhs_table'            => 'j_payment',
                'lhs_key'            => 'id',
                'rhs_module'        => 'C_Carryforward',
                'rhs_table'            => 'c_carryforward',
                'rhs_key'            => 'payment_id',
                'relationship_type'    => 'one-to-many',
            ),
            //Custom Relationship JUNIOR. Payment - Student Situation  By Lap Nguyen
            'j_payment_studentsituations' => array(
                'lhs_module'        => 'J_Payment',
                'lhs_table'            => 'j_payment',
                'lhs_key'            => 'id',
                'rhs_module'        => 'J_StudentSituations',
                'rhs_table'            => 'j_studentsituations',
                'rhs_key'            => 'payment_id',
                'relationship_type'    => 'one-to-many',
            ),
            //Custom Relationship JUNIOR. Payment - Sponsor  By Lap Nguyen
            'j_payment_j_sponsor' => array(
                'lhs_module'        => 'J_Payment',
                'lhs_table'            => 'j_payment',
                'lhs_key'            => 'id',
                'rhs_module'        => 'J_Sponsor',
                'rhs_table'            => 'j_sponsor',
                'rhs_key'            => 'payment_id',
                'relationship_type'    => 'one-to-many',
            ),
            //Custom Relationship JUNIOR. Moving - Transfer  By Lap Nguyen
            'j_payment_moving_transfer' => array(
                'lhs_module'        => 'J_Payment',
                'lhs_table'            => 'j_payment',
                'lhs_key'            => 'id',
                'rhs_module'        => 'J_Payment',
                'rhs_table'            => 'j_payment',
                'rhs_key'            => 'payment_out_id',
                'relationship_type'    => 'one-to-many',
            ),
            //Add Relationship Payment - Receipt (Split Payment)
            'payment_paymentdetails' => array(
                'lhs_module' => 'J_Payment',
                'lhs_table' => 'j_payment',
                'lhs_key' => 'id',
                'rhs_module' => 'J_PaymentDetail',
                'rhs_table' => 'j_paymentdetail',
                'rhs_key' => 'payment_id',
                'relationship_type' => 'one-to-many'
            ),
            //Add Relationship Payment - Loyalty
            'payment_loyaltys' => array(
                'lhs_module' => 'J_Payment',
                'lhs_table' => 'j_payment',
                'lhs_key' => 'id',
                'rhs_module' => 'J_Loyalty',
                'rhs_table' => 'j_loyalty',
                'rhs_key' => 'payment_id',
                'relationship_type' => 'one-to-many'
            ),
            //Add Relationship Payment - Commission
            'payment_coms' => array(
                'lhs_module' => 'J_Payment',
                'lhs_table' => 'j_payment',
                'lhs_key' => 'id',
                'rhs_module' => 'C_Commission',
                'rhs_table' => 'c_commission',
                'rhs_key' => 'payment_id',
                'relationship_type' => 'one-to-many'
            ),
            //Add Relationship Payment - Revenue (
            'ju_payment_revenue' => array(
                'lhs_module'        => 'J_Payment',
                'lhs_table'            => 'j_payment',
                'lhs_key'            => 'id',
                'rhs_module'        => 'C_DeliveryRevenue',
                'rhs_table'            => 'c_deliveryrevenue',
                'rhs_key'            => 'ju_payment_id',
                'relationship_type'    => 'one-to-many',
            ),
            //Add Relationship Payment - Invoices
            'payment_invoices' => array(
                'lhs_module' => 'J_Payment',
                'lhs_table' => 'j_payment',
                'lhs_key' => 'id',
                'rhs_module' => 'J_Invoice',
                'rhs_table' => 'j_invoice',
                'rhs_key' => 'payment_id',
                'relationship_type' => 'one-to-many'
            ),
        ),
        'optimistic_locking' => true,
        'unified_search' => true,
        'full_text_search' => false,
    );

    if (!class_exists('VardefManager')){
    }
    VardefManager::createVardef('J_Payment','J_Payment', array('basic','team_security','assignable','taggable'));
