<?php

$relationships = array (
  'account_paymentdetail_parent' => 
  array (
    'name' => 'account_paymentdetail_parent',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'J_PaymentDetail',
    'rhs_table' => 'j_paymentdetail',
    'rhs_key' => 'parent_id',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Accounts',
    'readonly' => true,
    'relationship_name' => 'account_paymentdetail_parent',
    'rhs_subpanel' => 'ForAccountsPaymentdetail_parent',
    'lhs_subpanel' => NULL,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'quote_paymentdetails' => 
  array (
    'name' => 'quote_paymentdetails',
    'lhs_module' => 'Quotes',
    'lhs_table' => 'quotes',
    'lhs_key' => 'id',
    'rhs_module' => 'J_PaymentDetail',
    'rhs_table' => 'j_paymentdetail',
    'rhs_key' => 'quote_id',
    'relationship_type' => 'one-to-many',
    'readonly' => true,
    'relationship_name' => 'quote_paymentdetails',
    'rhs_subpanel' => 'ForQuotesQuote_paymentdetails',
    'lhs_subpanel' => NULL,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'payment_paymentdetails' => 
  array (
    'name' => 'payment_paymentdetails',
    'lhs_module' => 'J_Payment',
    'lhs_table' => 'j_payment',
    'lhs_key' => 'id',
    'rhs_module' => 'J_PaymentDetail',
    'rhs_table' => 'j_paymentdetail',
    'rhs_key' => 'payment_id',
    'relationship_type' => 'one-to-many',
    'readonly' => true,
    'relationship_name' => 'payment_paymentdetails',
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'j_paymentdetail_modified_user' => 
  array (
    'name' => 'j_paymentdetail_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'J_PaymentDetail',
    'rhs_table' => 'j_paymentdetail',
    'rhs_key' => 'modified_user_id',
    'relationship_type' => 'one-to-many',
    'readonly' => true,
    'relationship_name' => 'j_paymentdetail_modified_user',
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'j_paymentdetail_created_by' => 
  array (
    'name' => 'j_paymentdetail_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'J_PaymentDetail',
    'rhs_table' => 'j_paymentdetail',
    'rhs_key' => 'created_by',
    'relationship_type' => 'one-to-many',
    'readonly' => true,
    'relationship_name' => 'j_paymentdetail_created_by',
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'j_paymentdetail_activities' => 
  array (
    'name' => 'j_paymentdetail_activities',
    'lhs_module' => 'J_PaymentDetail',
    'lhs_table' => 'j_paymentdetail',
    'lhs_key' => 'id',
    'rhs_module' => 'Activities',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'rhs_vname' => 'LBL_ACTIVITY_STREAM',
    'relationship_type' => 'many-to-many',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'J_PaymentDetail',
    'fields' => 
    array (
      'id' => 
      array (
        'name' => 'id',
        'type' => 'id',
        'len' => 36,
        'required' => true,
      ),
      'activity_id' => 
      array (
        'name' => 'activity_id',
        'type' => 'id',
        'len' => 36,
        'required' => true,
      ),
      'parent_type' => 
      array (
        'name' => 'parent_type',
        'type' => 'varchar',
        'len' => 100,
      ),
      'parent_id' => 
      array (
        'name' => 'parent_id',
        'type' => 'id',
        'len' => 36,
      ),
      'fields' => 
      array (
        'name' => 'fields',
        'type' => 'json',
        'dbType' => 'longtext',
        'required' => true,
      ),
      'date_modified' => 
      array (
        'name' => 'date_modified',
        'type' => 'datetime',
      ),
      'deleted' => 
      array (
        'name' => 'deleted',
        'vname' => 'LBL_DELETED',
        'type' => 'bool',
        'default' => '0',
      ),
    ),
    'readonly' => true,
    'relationship_name' => 'j_paymentdetail_activities',
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'paymentdetail_loyaltys' => 
  array (
    'name' => 'paymentdetail_loyaltys',
    'lhs_module' => 'J_PaymentDetail',
    'lhs_table' => 'j_paymentdetail',
    'lhs_key' => 'id',
    'rhs_module' => 'J_Loyalty',
    'rhs_table' => 'j_loyalty',
    'rhs_key' => 'paymentdetail_id',
    'relationship_type' => 'one-to-many',
    'readonly' => true,
    'relationship_name' => 'paymentdetail_loyaltys',
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'j_paymentdetail_following' => 
  array (
    'name' => 'j_paymentdetail_following',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'J_PaymentDetail',
    'rhs_table' => 'j_paymentdetail',
    'rhs_key' => 'id',
    'relationship_type' => 'many-to-many',
    'join_table' => 'subscriptions',
    'join_key_lhs' => 'created_by',
    'join_key_rhs' => 'parent_id',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'J_PaymentDetail',
    'user_field' => 'created_by',
    'readonly' => true,
    'relationship_name' => 'j_paymentdetail_following',
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'j_paymentdetail_favorite' => 
  array (
    'name' => 'j_paymentdetail_favorite',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'J_PaymentDetail',
    'rhs_table' => 'j_paymentdetail',
    'rhs_key' => 'id',
    'relationship_type' => 'many-to-many',
    'join_table' => 'dotbfavorites',
    'join_key_lhs' => 'modified_user_id',
    'join_key_rhs' => 'record_id',
    'relationship_role_column' => 'module',
    'relationship_role_column_value' => 'J_PaymentDetail',
    'user_field' => 'created_by',
    'readonly' => true,
    'relationship_name' => 'j_paymentdetail_favorite',
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'j_paymentdetail_assigned_user' => 
  array (
    'name' => 'j_paymentdetail_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'J_PaymentDetail',
    'rhs_table' => 'j_paymentdetail',
    'rhs_key' => 'assigned_user_id',
    'relationship_type' => 'one-to-many',
    'readonly' => true,
    'relationship_name' => 'j_paymentdetail_assigned_user',
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'receipt_payment' => 
  array (
    'name' => 'receipt_payment',
    'lhs_module' => 'J_PaymentDetail',
    'lhs_table' => 'j_paymentdetail',
    'lhs_key' => 'id',
    'rhs_module' => 'J_Payment',
    'rhs_table' => 'j_payment',
    'rhs_key' => 'receipt_id',
    'relationship_type' => 'one-to-one',
    'readonly' => true,
    'relationship_name' => 'receipt_payment',
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'invoice_paymentdetail' => 
  array (
    'name' => 'invoice_paymentdetail',
    'lhs_module' => 'J_Invoice',
    'lhs_table' => 'j_invoice',
    'lhs_key' => 'id',
    'rhs_module' => 'J_PaymentDetail',
    'rhs_table' => 'j_paymentdetail',
    'rhs_key' => 'invoice_id',
    'relationship_type' => 'one-to-many',
    'readonly' => true,
    'relationship_name' => 'invoice_paymentdetail',
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'j_paymentdetail_b_invoices_1' => 
  array (
    'rhs_label' => 'Invoices',
    'lhs_label' => 'Receipts',
    'lhs_subpanel' => 'default',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'J_PaymentDetail',
    'rhs_module' => 'B_Invoices',
    'relationship_type' => 'many-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'j_paymentdetail_b_invoices_1',
  ),
);