<?php



    $dictionary['J_PaymentDetail'] = array(
        'table' => 'j_paymentdetail',
        'audited' => true,
        'activity_enabled' => false,
        'duplicate_merge' => true,
        'fields' => array (
            'payment_amount' =>
            array (
                'required' => true,
                'name' => 'payment_amount',
                'vname' => 'LBL_PAYMENT_AMOUNT',
                'type' => 'currency',
                'massupdate' => 1,
                'no_default' => false,
                'comments' => '',
                'help' => 'Payment Amount',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 26,
                'min' => 1,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'numeric_range_search_dom',
                'precision' => 6,
                'default' => '0',
            ),
            'payment_method_fee' =>
            array (
                'required' => false,
                'name' => 'payment_method_fee',
                'vname' => 'LBL_METHOD_FEE',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Payment Amount',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 13,
                'min' => 1,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'numeric_range_search_dom',
                'precision' => 2,
                'default' => '',
                'related_fields' =>
                    array (
                        0 => 'currency_id',
                        1 => 'base_rate',
                    ),
            ),
            'payment_date' =>
            array (
                'required' => false,
                'name' => 'payment_date',
                'vname' => 'LBL_PAYMENT_DATE',
                'type' => 'date',
                'massupdate' => 1,
                'no_default' => false,
                'comments' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'date_range_search_dom',
            ),
            'level' => array (
                'name' => 'level',
                'vname' => 'LBL_LEVEL',
                'type' => 'multienum',
                'dbType' => 'varchar',
                'isMultiSelect' => true,
                'audited' => false,
                'options' => 'level_program_list',
                'default' => '',
                'len' => 255,
            ),
            'kind_of_course' => array (
                'name' => 'kind_of_course',
                'vname' => 'LBL_KIND_OF_COURSE',
                'type' => 'multienum',
                'dbType' => 'varchar',
                'isMultiSelect' => true,
                'audited' => false,
                'options' => 'kind_of_course_list',
                'default' => '',
                'len' => 255,
            ),
            'expired_date' =>
            array (
                'required' => true,
                'name' => 'expired_date',
                'vname' => 'LBL_EXPIRED_DATE',
                'type' => 'date',
                'massupdate' => 1,
                'no_default' => false,
                'comments' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'date_range_search_dom',
            ),

            'before_discount' =>
            array (
                'name' => 'before_discount',
                'vname' => 'LBL_BEFORE_DISCOUNT',
                'type' => 'currency',
                'len' => 13,
                'precision' => 2,
            ),
            'is_first' =>
            array (
                'name' => 'is_first',
                'vname' => 'LBL_IS_FIRST',
                'type' => 'bool',
                'default' => '0',
            ),
            'discount_amount' =>
            array (
                'name' => 'discount_amount',
                'vname' => 'LBL_DISCOUNT_AMOUNT',
                'type' => 'currency',
                'len' => 13,
                'precision' => 6,
            ),
            'sponsor_amount' =>
            array (
                'name' => 'sponsor_amount',
                'vname' => 'LBL_SPONSOR_AMOUNT',
                'type' => 'currency',
                'len' => 26,
                'precision' => 6,
            ),
            'loyalty_amount' =>
            array (
                'name' => 'loyalty_amount',
                'vname' => 'LBL_LOYALTY_AMOUNT',
                'type' => 'currency',
                'len' => 26,
                'precision' => 6,
            ),
            'payment_method' =>
            array (
                'required' => false,
                'name' => 'payment_method',
                'vname' => 'LBL_PAYMENT_METHOD',
                'type' => 'enum',
                'massupdate' => 0,
                'default' => '',
                'no_default' => false,
                'comments' => '',
                'help' => 'Payment Method',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 50,
                'size' => '20',
                'options' => 'payment_method_list',
                'studio' => 'visible',
                'dependency' => false,
            ),
            'content_vat_invoice' =>
            array (
                'name' => 'content_vat_invoice',
                'vname' => 'LBL_CONTENT_VAT_INVOICE',
                'type' => 'text',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Method Note',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '255',
                'size' => '20',
            ),
            'method_note' =>
            array (
                'required' => false,
                'name' => 'method_note',
                'vname' => 'LBL_METHOD_NOTE',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Method Note',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '100',
                'size' => '20',
            ),
            'pos_code' =>
            array (
                'required' => false,
                'name' => 'pos_code',
                'vname' => 'LBL_POS_CODE',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Method Note',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '100',
                'size' => '20',
            ),
            'inv_code' =>
            array (
                'required' => false,
                'name' => 'inv_code',
                'vname' => 'LBL_INV_CODE',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => 'Method Note',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '100',
                'size' => '20',
            ),
            'card_type' =>
            array (
                'required' => false,
                'name' => 'card_type',
                'vname' => 'LBL_CARD_TYPE',
                'type' => 'enum',
                'massupdate' => 0,
                'default' => '',
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'options' => 'card_type_payments_list',
                'studio' => 'visible',
                'dependency' => false,
            ),
            'custom_button' =>
            array (
                'name' => 'custom_button',
                'vname' => 'Button',
                'type' => 'varchar',
                'len' => '1',
                'studio' => 'visible',
                'source' => 'non-db',
            ),
            'is_discount' =>
            array (
                'name' => 'is_discount',
                'vname' => 'LBL_IS_DISCOUNT',
                'type' => 'bool',
                'comments' => 'comment',
                'help' => 'help',
                'importable' => 'true',
                'duplicate_merge' => 'enabled',
                'duplicate_merge_dom_value' => '1',
                'audited' => false,
                'reportable' => true,
            ),
            'printed_date' =>
            array (
                'required' => true,
                'name' => 'printed_date',
                'vname' => 'LBL_PRINTED_DATE',
                'type' => 'date',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'date_range_search_dom',
            ),
            'status' =>
            array (
                'required' => false,
                'name' => 'status',
                'vname' => 'LBL_STATUS',
                'type' => 'enum',
                'massupdate' => 0,
                'no_default' => false,
                'default' => 'Unpaid',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => 10,
                'size' => '20',
                'options' => 'status_paymentdetail_list',
                'studio' => 'visible',
                'dependency' => false,
            ),

            'payment_no' =>
            array (
                'required' => false,
                'name' => 'payment_no',
                'vname' => 'LBL_PAYMENT_NO',
                'type' => 'int',
                'massupdate' => 0,
                'default' => '',
                'no_default' => false,
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '10',
                'size' => '20',
                'enable_range_search' => false,
                'disable_num_format' => '',
                'min' => false,
                'max' => false,
            ),

            'numeric_vat_no' =>
            array (
                'required' => true,
                'name' => 'numeric_vat_no',
                'vname' => 'LBL_INVOICE_NUMBER_INT',
                'type' => 'int',
                'massupdate' => 0,
                'no_default' => false,
                'default' => 'NULL',
                'comments' => '',
                'help' => 'VAT No Int',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'calculated' => false,
                'len' => '10',
                'size' => '20',
                'enable_range_search' => true,
                'options' => 'numeric_range_search_dom',
            ),
            //bổ sung Sale type cho receipt
            'sale_type' =>
            array (
                'required' => false,
                'name' => 'sale_type',
                'vname' => 'LBL_SALE_TYPE',
                'type' => 'enum',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'default' => '',
                'calculated' => false,
                'len' => 100,
                'size' => '20',
                'options' => 'sale_type_list',
                'dependency' => false,
            ),
            'sale_type_date' =>
            array (
                'required' => true,
                'name' => 'sale_type_date',
                'vname' => 'LBL_SALE_TYPE_DATE',
                'type' => 'date',
                'massupdate' => false,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'pii' => false,
                'calculated' => false,
                'size' => '20',
                'enable_range_search' => false,
            ),

            //Add Relationship Payment - Receipt (Split Payment)
            'payment_id' => array(
                'name' => 'payment_id',
                'vname' => 'LBL_PAYMENT_ID',
                'type' => 'id',
                'required'=>false,
                'reportable'=>false,
                'comment' => ''
            ),

            'payment_name' => array(
                'name' => 'payment_name',
                'rname' => 'name',
                'id_name' => 'payment_id',
                'vname' => 'LBL_PAYMENT_NAME',
                'type' => 'relate',
                'link' => 'payment_link',
                'table' => 'j_payment',
                'isnull' => 'true',
                'module' => 'J_Payment',
                'dbType' => 'varchar',
                'len' => 'id',
                'reportable'=>true,
                'source' => 'non-db',
            ),

            'payment_link' => array(
                'name' => 'payment_link',
                'type' => 'link',
                'relationship' => 'payment_paymentdetails',
                'link_type' => 'one',
                'side' => 'right',
                'source' => 'non-db',
                'vname' => 'LBL_PAYMENT_NAME',
            ),

            //Add Relationship Invoice - Receipt
            'invoice_id' => array(
                'name' => 'invoice_id',
                'vname' => 'LBL_INVOICE_ID',
                'type' => 'id',
                'required'=>false,
                'reportable'=>false,
                'comment' => ''
            ),

            'invoice_name' => array(
                'name' => 'invoice_name',
                'rname' => 'name',
                'id_name' => 'invoice_id',
                'vname' => 'LBL_INVOICE_NUMBER',
                'type' => 'relate',
                'link' => 'invoice_link',
                'table' => 'j_invoice',
                'isnull' => 'true',
                'module' => 'J_Invoice',
                'dbType' => 'varchar',
                'len' => 'id',
                'reportable'=>true,
                'source' => 'non-db',
            ),

            'invoice_link' => array(
                'name' => 'invoice_link',
                'type' => 'link',
                'relationship' => 'invoice_paymentdetail',
                'link_type' => 'one',
                'side' => 'right',
                'source' => 'non-db',
                'vname' => 'LBL_INVOICE_NUMBER',
            ),
            //  Invoice - Receipt

            //Contract - Payment
//            'contract_id' => array(
//                'name' => 'contract_id',
//                'vname' => 'LBL_CONTRACT_ID',
//                'type' => 'id',
//                'required'=>false,
//                'reportable'=>false,
//                'comment' => ''
//            ),
//            'contract_name' => array(
//                'name' => 'contract_name',
//                'rname' => 'name',
//                'id_name' => 'contract_id',
//                'vname' => 'LBL_CONTRACT_NAME',
//                'type' => 'relate',
//                'link' => 'contract_link',
//                'table' => 'contracts',
//                'isnull' => 'true',
//                'module' => 'Contracts',
//                'dbType' => 'varchar',
//                'len' => 'id',
//                'reportable'=>true,
//                'source' => 'non-db',
//            ),
//            'contract_link' => array(
//                'name' => 'contract_link',
//                'type' => 'link',
//                'relationship' => 'contract_paymentdetails',
//                'link_type' => 'one',
//                'side' => 'right',
//                'source' => 'non-db',
//                'vname' => 'LBL_CONTRACT_NAME',
//            ),
            //Custom Relationship JUNIOR. Student  - Receipt (1-n)  By Lap Nguyen

            //Custom Related field Printed By
//            'printed_user_id' => array(
//                'name' => 'printed_user_id',
//                'rname' => 'user_name',
//                'id_name' => 'printed_user_id',
//                'vname' => 'LBL_PRINTEDBY',
//                'type' => 'assigned_user_name',
//                'table' => 'users',
//                'isnull' => false,
//                'group' => 'printed_user_name',
//                'dbType' => 'id',
//                'reportable' => true,
//                'comment' => '',
//                'massupdate' => false,
//                'duplicate_on_record_copy' => 'no',
//                'readonly' => true,
//                'processes' => array(
//                    'types' => array(
//                        'RR' => false,
//                        'ALL' => true,
//                    ),
//                ),
//            ),
//            'printed_user_name' => array(
//                'name' => 'printed_user_name',
//                'vname' => 'LBL_PRINTEDBY',
//                'type' => 'relate',
//                'reportable' => false,
//                'source' => 'non-db',
//                'rname' => 'full_name',
//                'table' => 'users',
//                'id_name' => 'printed_user_id',
//                'module' => 'Users',
//                'link' => 'printed_user_link',
//                'duplicate_merge' => 'disabled',
//                'massupdate' => false,
//                'duplicate_on_record_copy' => 'no',
//                'readonly' => true,
//                'sort_on' => array('last_name'),
//                'exportable' => true,
//            ),
//            'printed_user_link' => array(
//                'name' => 'printed_user_link',
//                'type' => 'link',
//                'relationship' => '_printed_user',
//                'vname' => 'LBL_PRINTED_BY_USER',
//                'link_type' => 'one',
//                'module' => 'Users',
//                'bean_name' => 'User',
//                'source' => 'non-db',
//                'side' => 'right',
//            ),
//            //Printed By
//
//            'student_name' => array(
//                'required'  => false,
//                'source'    => 'non-db',
//                'name'      => 'student_name',
//                'vname'     => 'LBL_STUDENT_NAME',
//                'type'      => 'relate',
//                'rname'     => 'name',
//                'id_name'   => 'student_id',
//                'massupdate' => false,
//                'join_name' => 'contacts',
//                'link'      => 'ju_student',
//                'table'     => 'contacts',
//                'isnull'    => 'true',
//                'module'    => 'Contacts',
//            ),
//
//            'student_id' => array(
//                'name'              => 'student_id',
//                'rname'             => 'id',
//                'vname'             => 'LBL_STUDENT_ID',
//                'type'              => 'id',
//                'table'             => 'contacts',
//                'isnull'            => 'true',
//                'module'            => 'Contacts',
//                'dbType'            => 'id',
//                'reportable'        => false,
//                'massupdate'        => false,
//                'duplicate_merge'   => 'disabled',
//            ),
//
//            'ju_student' => array(
//                'name'          => 'ju_student',
//                'type'          => 'link',
//                'relationship'  => 'student_paymentdetail',
//                'module'        => 'Contacts',
//                'bean_name'     => 'Contact',
//                'source'        => 'non-db',
//                'vname'         => 'LBL_STUDENT_NAME',
//            ),

            //Add Relationship Payment - Loyalty
            'loyalty_link'=>array(
                'name' => 'loyalty_link',
                'type' => 'link',
                'relationship' => 'paymentdetail_loyaltys',
                'module' => 'J_Loyalty',
                'bean_name' => 'J_Loyalty',
                'source' => 'non-db',
                'vname' => 'LBL_LOYALTY',
            ),
            //Custom Relationship. Receipt - Commission
            'commission_link'=>array(
                'name' => 'commission_link',
                'type' => 'link',
                'relationship' => 'pmd_coms',
                'module' => 'C_Commission',
                'bean_name' => 'C_Commission',
                'source' => 'non-db',
                'vname' => 'LBL_COMMISSION',
            ),


            'bank_account' =>
            array (
                'required' => false,
                'name' => 'bank_account',
                'vname' => 'LBL_BANK_ACCOUNT',
                'type' => 'enum',
                'massupdate' => 0,
                'importable' => 'true',
                'audited' => false,
                'reportable' => true,
                'len' => 200,
                'size' => '20',
                'options' => 'bank_name_list',
            ),
            'reference_document' =>
            array (
                'required' => false,
                'name' => 'reference_document',
                'vname' => 'LBL_REFERENCE_DOCUMENT',
                'type' => 'varchar',
                'importable' => 'true',
                'audited' => false,
                'reportable' => true,
                'len' => 200,
                'size' => '20',
            ),
            'reference_number' =>
            array (
                'required' => false,
                'name' => 'reference_number',
                'vname' => 'LBL_REFERENCE_NUMBER',
                'type' => 'varchar',
                'importable' => 'true',
                'audited' => false,
                'reportable' => true,
                'len' => 200,
                'size' => '20',
            ),
        ),
        'indices' => array (
            array(
                'name' => 'idx_payment_id',
                'type' => 'index',
                'fields'=> array('payment_id'),
            ),
            array(
                'name' => 'idx_invoice_id',
                'type' => 'index',
                'fields'=> array('invoice_id'),
            ),
        ),
        'relationships' => array (
            //Add Relationship Receipt - Loyalty
            'paymentdetail_loyaltys' => array(
                'lhs_module' => 'J_PaymentDetail',
                'lhs_table' => 'j_paymentdetail',
                'lhs_key' => 'id',
                'rhs_module' => 'J_Loyalty',
                'rhs_table' => 'j_loyalty',
                'rhs_key' => 'paymentdetail_id',
                'relationship_type' => 'one-to-many'
            ),

            //Custom Relationship. Receipt - Commission
            'pmd_coms' => array(
                'lhs_module'        => 'J_PaymentDetail',
                'lhs_table'            => 'j_paymentdetail',
                'lhs_key'            => 'id',
                'rhs_module'        => 'C_Commission',
                'rhs_table'            => 'c_commission',
                'rhs_key'            => 'pmd_id',
                'relationship_type'    => 'one-to-many',
            ),
        ),
        'optimistic_locking' => true,
        'unified_search' => true,
        'full_text_search' => true,
    );

    if (!class_exists('VardefManager')){
    }
    VardefManager::createVardef('J_PaymentDetail','J_PaymentDetail', array('basic','team_security','assignable','taggable'));
